<?php
declare(strict_types=1);

function adaExtraReviewedStateProfiles(): array
{
    $reviewed = [
        'IA' => ['Iowa', 'Iowa law gives people with disabilities full and equal access to public places and accommodations with service dogs and assistive animals, and separately gives trainers access while training service dogs and assistive animals.', ['Iowa protects access to public facilities and accommodations for people with disabilities using service dogs or assistive animals.', 'Trainers of service dogs and assistive animals are protected while training in listed public places.', 'Extra charges are barred, but the person or trainer may be liable for damage.', 'Federal ADA rules still apply in ADA-covered public accommodations.'], 'Iowa recognizes trainer access while training service dogs and assistive animals.', 'Housing may involve Iowa civil-rights rules plus federal FHA reasonable-accommodation rules.', 'Iowa Code Chapter 216C', 'https://www.legis.iowa.gov/docs/code/216C.pdf'],
        'IL' => ['Illinois', 'Illinois law protects public-access rights for people using guide, hearing, or support dogs and recognizes access for trainers affiliated with recognized training programs. Illinois also has separate housing and misrepresentation provisions.', ['Illinois protects access to public accommodations and other covered places for people with disabilities accompanied by trained service dogs.', 'Illinois recognizes guide, hearing, and support dogs in state law.', 'Trainers affiliated with recognized training programs may have access while training in covered places.', 'Extra charges are barred, but damage liability may apply.'], 'Illinois training access is tied to recognized training programs and trainer status in the reviewed state-law materials.', 'Housing may involve Illinois assistance-animal rules plus federal FHA reasonable-accommodation rules.', 'Illinois White Cane Law / Service Animal Access Act materials', 'https://www.ilga.gov/legislation/ilcs/ilcs3.asp?ActID=2104&ChapterID=59'],
        'IN' => ['Indiana', 'Indiana law protects access for people with disabilities accompanied by guide dogs or service animals and recognizes training access for service animals in training.', ['Indiana protects access to public accommodations and public facilities for people with disabilities using service animals.', 'The state uses guide dog and service animal language across related provisions.', 'Service-animal-in-training access is recognized in state law.', 'Extra charges may be barred, while damage liability may apply.'], 'Indiana recognizes service-animal-in-training access; verify trainer and setting-specific requirements before relying on it.', 'Housing may involve Indiana civil-rights/fair-housing rules plus federal FHA reasonable-accommodation rules.', 'Indiana Code Title 16 and Title 22 service animal provisions', 'https://iga.in.gov/laws/2024/ic/titles/016#16-32-3'],
        'MI' => ['Michigan', 'Michigan law protects access for people with disabilities using service animals and recognizes service animals in training in public accommodations when handled by certain trainers. Michigan also addresses voluntary service-animal identification.', ['Michigan public-accommodation law protects people with disabilities using service animals.', 'Service animals in training may be covered when handled by a trainer, raiser, or representative of a service-animal training organization.', 'Michigan has voluntary service-animal identification provisions, but ADA public-access rights do not depend on registration.', 'Misrepresentation and interference provisions may apply under Michigan law.'], 'Michigan training access is tied to trainer/raiser/organization-related status in the reviewed materials.', 'Housing may involve Michigan fair-housing rules plus federal FHA reasonable-accommodation rules.', 'Michigan service animal laws / MDCR service animal guidance', 'https://www.michigan.gov/mdcr/divisions/ada-compliance/service-animals'],
        'MN' => ['Minnesota', 'Minnesota law protects access for people with disabilities accompanied by service animals and recognizes access for trainers of service animals in training in public places.', ['Minnesota protects access for people with disabilities accompanied by service animals.', 'Service animals in training and trainers are recognized in state law.', 'Public accommodations may not require extra charges because of the service animal.', 'Handlers may remain responsible for control and damage.'], 'Minnesota recognizes trainers and service animals in training; confirm setting-specific details before relying on training access.', 'Housing may involve Minnesota human-rights/fair-housing rules plus federal FHA reasonable-accommodation rules.', 'Minnesota Statutes Chapter 363A service animal provisions', 'https://www.revisor.mn.gov/statutes/cite/363A.19'],
        'ND' => ['North Dakota', 'North Dakota law protects access for individuals with disabilities accompanied by service animals and recognizes service animals in training in public accommodations when accompanied by a trainer.', ['North Dakota protects access to public accommodations for people with disabilities using service animals.', 'Service animals in training may be admitted when accompanied by a trainer.', 'A trainer or handler can be liable for damage caused by the animal.', 'Federal ADA two-question and documentation limits remain the baseline in ADA-covered places.'], 'North Dakota recognizes service-animal-in-training access when accompanied by a trainer, subject to control and setting-specific rules.', 'Housing may involve North Dakota fair-housing rules plus federal FHA reasonable-accommodation rules.', 'North Dakota Century Code Chapter 25-13', 'https://ndlegis.gov/cencode/t25c13.pdf'],
        'OH' => ['Ohio', 'Ohio law protects people with disabilities accompanied by assistance dogs in public accommodations and housing accommodations, and also recognizes trainers of assistance dogs in training.', ['Ohio protects access for people with disabilities using trained assistance dogs.', 'Ohio has public-accommodation and housing-accommodation language.', 'Trainers of assistance dogs are recognized in state law.', 'Extra charges are barred, but damage liability may apply.'], 'Ohio recognizes assistance-dog trainers and assistance dogs in training; verify exact trainer and setting requirements.', 'Ohio housing access is addressed in state law, with federal FHA rules also relevant.', 'Ohio Revised Code § 955.43', 'https://codes.ohio.gov/ohio-revised-code/section-955.43'],
        'PA' => ['Pennsylvania', 'Pennsylvania law protects access for people using guide, signal, or service dogs and recognizes access for handlers or trainers of service dogs in training under state law.', ['Pennsylvania protects access for people with disabilities accompanied by guide, signal, or service dogs.', 'Service dogs in training and handlers/trainers may be recognized in state access law.', 'Extra charges are generally barred, while damage liability may apply.', 'Federal ADA limits on documentation and inquiry still apply in ADA-covered public accommodations.'], 'Pennsylvania recognizes service-dog-in-training access in reviewed state-law materials; verify trainer and identification details by setting.', 'Housing may involve Pennsylvania human-relations/fair-housing rules plus federal FHA reasonable-accommodation rules.', 'Pennsylvania Human Relations Act / service animal access resources', 'https://www.pa.gov/agencies/phrc/programs-and-services/disability-rights.html'],
        'WI' => ['Wisconsin', 'Wisconsin law protects access for people with disabilities accompanied by service animals and recognizes service animals in training accompanied by trainers in public places and accommodations.', ['Wisconsin protects access to public places and accommodations for people with disabilities using service animals.', 'Service animals in training accompanied by trainers are recognized under state law.', 'Extra charges are barred, though handlers/trainers may be liable for damage.', 'Federal ADA rules remain the baseline for ADA-covered public accommodations.'], 'Wisconsin recognizes service animals in training when accompanied by trainers in covered public places.', 'Housing may involve Wisconsin open-housing rules plus federal FHA reasonable-accommodation rules.', 'Wisconsin Statutes § 106.52', 'https://docs.legis.wisconsin.gov/statutes/statutes/106/52'],
    ];

    $profiles = [];
    foreach ($reviewed as $code => $p) {
        $profiles[$code] = adaReviewedStateProfile($code, $p[0], $p[1], $p[2], $p[3], $p[4], $p[5], $p[6]);
    }

    return $profiles;
}
