<?php
declare(strict_types=1);

function adaStateNames(): array
{
    return [
        'AL'=>'Alabama','AK'=>'Alaska','AZ'=>'Arizona','AR'=>'Arkansas','CA'=>'California','CO'=>'Colorado','CT'=>'Connecticut','DE'=>'Delaware','DC'=>'District of Columbia','FL'=>'Florida','GA'=>'Georgia','HI'=>'Hawaii','ID'=>'Idaho','IL'=>'Illinois','IN'=>'Indiana','IA'=>'Iowa','KS'=>'Kansas','KY'=>'Kentucky','LA'=>'Louisiana','ME'=>'Maine','MD'=>'Maryland','MA'=>'Massachusetts','MI'=>'Michigan','MN'=>'Minnesota','MS'=>'Mississippi','MO'=>'Missouri','MT'=>'Montana','NE'=>'Nebraska','NV'=>'Nevada','NH'=>'New Hampshire','NJ'=>'New Jersey','NM'=>'New Mexico','NY'=>'New York','NC'=>'North Carolina','ND'=>'North Dakota','OH'=>'Ohio','OK'=>'Oklahoma','OR'=>'Oregon','PA'=>'Pennsylvania','RI'=>'Rhode Island','SC'=>'South Carolina','SD'=>'South Dakota','TN'=>'Tennessee','TX'=>'Texas','UT'=>'Utah','VT'=>'Vermont','VA'=>'Virginia','WA'=>'Washington','WV'=>'West Virginia','WI'=>'Wisconsin','WY'=>'Wyoming',
    ];
}

function adaFederalLawProfile(): array
{
    return [
        'title'=>'Federal ADA baseline',
        'summary'=>'Under the ADA, a service animal is a dog individually trained to do work or perform tasks for a person with a disability. Staff may ask only the two ADA questions when the need is not obvious. Certification, registration papers, medical records, special ID, and task demonstrations are not required for public access.',
        'bullets'=>[
            'Allowed questions: is the dog required because of a disability, and what work or task has the dog been trained to perform?',
            'Not allowed: diagnosis questions, medical records, certification demands, special ID requirements, or forced task demonstrations.',
            'A service animal may be excluded if it is out of control and not effectively corrected, or if it is not housebroken.',
            'The ADA does not recognize service animals in training for public access, but state law may provide access for training teams.',
        ],
        'source_label'=>'ADA.gov Service Animals FAQ','source_url'=>'https://www.ada.gov/resources/service-animals-faqs/','last_reviewed'=>'2026-05-05',
    ];
}

function adaDefaultStateLawProfile(string $stateCode, string $stateName): array
{
    return [
        'state_code'=>$stateCode,'state_name'=>$stateName,'status'=>'pending',
        'summary'=>'GuidePaw has not yet added a reviewed state-specific summary for this state. Use the federal ADA baseline above and verify state or local rules through an official state source before relying on them.',
        'bullets'=>['Federal ADA public-access rules still apply in covered public places.','State rules may differ for service animals in training, housing, penalties, schools, workplaces, transit, or misrepresentation.','Use this as a reminder card, not legal advice.'],
        'training_note'=>'State-specific service-dog-in-training rule not reviewed yet.','housing_note'=>'Housing may involve separate federal and state reasonable-accommodation rules.','source_label'=>'State law source pending review','source_url'=>'','last_reviewed'=>'Pending',
    ];
}

function adaReviewedStateProfile(string $code, string $name, string $summary, array $bullets, string $trainingNote, string $housingNote, string $sourceLabel, string $sourceUrl): array
{
    return ['state_code'=>$code,'state_name'=>$name,'status'=>'reviewed','summary'=>$summary,'bullets'=>$bullets,'training_note'=>$trainingNote,'housing_note'=>$housingNote,'source_label'=>$sourceLabel,'source_url'=>$sourceUrl,'last_reviewed'=>'2026-05-05'];
}

function adaStateLawProfiles(): array
{
    $profiles = [];
    foreach (adaStateNames() as $code => $name) $profiles[$code] = adaDefaultStateLawProfile($code, $name);

    $reviewed = [
        'AL'=>['Alabama','Alabama law gives individuals with disabilities the right to be accompanied by a service animal in public accommodations, including public and private schools, and recognizes rights for service-animal trainers while training.',['Service animals must be under handler control unless disability or task work prevents tether use.','A trainer engaged in training has the same public-accommodation access rights and damage liability.','A service animal in training must have visible written identification readable from a distance.','Misrepresentation signage and penalties are addressed separately in state law.'],'Alabama training access is recognized, with visible-identification and trainer-qualification language.','Housing may involve Alabama access rules plus federal FHA reasonable-accommodation rules.','Alabama Code § 21-7-4','https://law.justia.com/codes/alabama/2019/title-21/chapter-7/section-21-7-4/'],
        'AR'=>['Arkansas','Arkansas protects access for people with disabilities accompanied by trained service animals and separately protects dog trainers while training guide, signal, or service dogs.',['Access covers public ways, public places, public accommodations, and housing accommodations.','Dog trainers in the act of training may not be denied access to listed public places because of the dog.','No extra charge may be required, but damage liability may apply.','Misrepresentation of a service animal or service animal-in-training can carry a civil penalty.'],'Arkansas recognizes access for dog trainers actively training guide, signal, or service dogs.','Housing accommodations are mentioned in state access language, with federal FHA rules also relevant.','Arkansas Code §§ 20-14-304 and 20-14-308','https://law.justia.com/codes/arkansas/title-20/subtitle-2/chapter-14/subchapter-3/section-20-14-308/'],
        'AZ'=>['Arizona','Arizona public-accommodation law defines a service animal as a dog or miniature horse individually trained, or in training, to perform disability-related work or tasks.',['Dogs and miniature horses that are trained or in training may qualify.','Public accommodations may not require service-animal identification.','Only limited task-related questions are allowed when the need is not obvious.','Emotional support or comfort alone does not meet the task-work standard.'],'Arizona includes animals in training within the service-animal definition for public-access purposes.','Housing may involve Arizona and federal FHA reasonable-accommodation rules.','Arizona HB2255 / service animal public-place language','https://www.azleg.gov/legtext/52leg/2r/laws/0099.htm'],
        'CA'=>['California','California uses a task-based service-animal definition and public resources emphasize that registration or certification is not required under the ADA framework.',['California Health and Safety Code § 113903 includes dogs trained or in training for disability-related tasks.','The cited section does not include other species.','Comfort or companionship alone does not meet the task-work standard.','California public guidance repeats the ADA two-question framework.'],'California recognizes service animals in training in the cited definition, but access may depend on setting and civil-rights context.','Housing may involve California fair-housing rules plus federal FHA rules.','California Health & Safety Code § 113903 / CA DOR','https://dor.ca.gov/Home/SupportAnimals'],
        'CO'=>['Colorado','Colorado grants access for trained service animals and for trainers or people with disabilities accompanied by animals being trained as service animals.',['Colorado covers public accommodations, public-entity programs, public transportation, employment, housing, and other public places.','Trainers of service animals have access rights.','Extra charges are barred for service animals and animals in training.','Common-carrier rules may require visible identification for animals in training.'],'Colorado training access is broad, but transportation may add identification requirements.','Colorado housing access is included, with federal FHA rules also relevant.','Colorado Revised Statutes § 24-34-803','https://law.justia.com/codes/colorado/title-24/principal-departments/article-34/part-8/section-24-34-803/'],
        'FL'=>['Florida','Florida protects public-accommodation and housing access for service animals, limits public-accommodation service animals to dogs or miniature horses, and recognizes trainers while training.',['Florida public accommodations must permit service animals used by people with disabilities.','Training documentation cannot be required as a precondition for access.','Trainers of service animals have the same public-facility access rights and liability while training.','Extra compensation for a service animal is barred in housing, though damage liability may apply.'],'Florida expressly recognizes trainer access while training service animals.','Florida includes housing-accommodation language, with federal FHA rules also relevant.','Florida Statutes § 413.08','https://www.flsenate.gov/Laws/Statutes/2024/413.08'],
        'GA'=>['Georgia','Georgia grants equal access to public accommodations and transportation for covered persons accompanied by guide dogs or service dogs, and recognizes trainers while training.',['Access includes transportation, lodging, public accommodations, amusement or resort places, and other public places.','Covered persons may be accompanied by a guide dog or service dog.','Extra charges may not be required, but damage liability may apply.','Georgia has separate training-access language for trainers.'],'Georgia recognizes trainers of guide dogs or service dogs while training, subject to state requirements.','Housing may involve Georgia service-dog rules plus federal FHA rules.','Georgia Code §§ 30-4-2 and 30-4-2.1','https://law.justia.com/codes/georgia/title-30/chapter-4/section-30-4-2/'],
        'ID'=>['Idaho','Idaho requires public accommodations to permit service dogs and separately protects access for dogs-in-training with control, grooming, liability, and visible-identification requirements.',['Service dogs must be permitted for individuals with disabilities or authorized handlers.','Exclusion may apply when out of control or not housebroken.','Dogs-in-training have public-accommodation and public-transportation access.','Dogs-in-training must be controlled and visually identified.'],'Idaho training access includes leash/control and visible-identification requirements.','Housing may involve Idaho and federal FHA rules.','Idaho Code §§ 56-704A and 18-5812B','https://law.justia.com/codes/idaho/title-18/chapter-58/section-18-5812b/'],
        'KS'=>['Kansas','Kansas gives professional trainers from recognized training centers access while training assistance dogs in listed public places.',['Professional trainers from recognized training centers may access listed places while training.','Trainer damage liability applies.','Comfort or emotional support animals are distinct from trained assistance dogs.','Federal ADA rules still apply in covered public accommodations.'],'Kansas training access is narrower and tied to professional trainers from recognized training centers.','Housing may involve federal FHA accommodation rules and Kansas-specific issues.','Kansas Statutes § 39-1109','https://www.kslegislature.gov/li/b2025_26/statute/039_000_0000_chapter/039_011_0000_article/039_011_0009_section/039_011_0009_k/'],
        'KY'=>['Kentucky','Kentucky reviewed content currently focuses on assistance-animal housing accommodations and misrepresentation. Public-access questions should rely on the federal ADA baseline unless a more protective Kentucky public-access rule applies.',['Kentucky housing law defines assistance animals to include task-trained service animals and emotional support animals.','Housing documentation and therapeutic-relationship rules may apply in accommodation requests.','Misrepresentation of an assistance animal is addressed in the housing statute.','Federal ADA public-accommodation rules remain the baseline for public access.'],'Kentucky service-animal-in-training public-access rule is not confirmed in this reviewed profile; verify separately before relying on training access.','Kentucky has reviewed housing-accommodation language for assistance animals in dwellings.','KRS § 383.085','https://apps.legislature.ky.gov/law/statutes/statute.aspx?id=49072'],
        'LA'=>['Louisiana','Louisiana protects access for qualified guide or service dogs in public accommodations, conveyances, and housing, and gives trainers and puppy raisers access during training.',['Public accommodations and conveyances are covered.','Housing protections are included.','Trainers and puppy raisers have access during training.','Misrepresentation language exists for service dogs and service dogs-in-training.'],'Louisiana expressly gives trainers and puppy raisers access while training.','Louisiana housing law bars extra compensation but allows damage liability.','Louisiana Revised Statutes §§ 21:52 and 46:1955','https://law.justia.com/codes/louisiana/revised-statutes/title-46/rs-46-1955/'],
        'MO'=>['Missouri','Missouri defines service dogs to include dogs being trained or already trained for disability-related work or tasks, and grants access to recognized trainers and service-dog team members while training.',['The service-dog definition includes dogs being trained.','Recognized trainers may access listed premises while training.','Service-dog team members may have training access under state law.','Damage liability may apply.'],'Missouri training access is tied to recognized training centers or service-dog team members.','Housing may involve Missouri rules plus federal FHA accommodation rules.','Missouri Revised Statutes §§ 209.152 and 209.200','https://law.justia.com/codes/missouri/title-xii/chapter-209/section-209-152/'],
        'MS'=>['Mississippi','Mississippi protects access for covered disabled persons using support animals specifically trained for assistance in day-to-day activities; federal ADA rules remain important because state language is narrower in some respects.',['Covered categories include blind, mobility-impaired, veterans with PTSD, and hearing-impaired persons.','The animal must be specifically trained for guide, leader, listener, or other necessary assistance.','Public accommodations covered by ADA must also follow federal rules.','Emotional support alone does not meet the ADA public-access task-work standard.'],'Mississippi service-animal-in-training access was not confirmed in the reviewed public-access section.','Housing may involve Mississippi support-animal rules plus federal FHA rules.','Mississippi Code § 43-6-155','https://law.justia.com/codes/mississippi/title-43/chapter-6/article-5/section-43-6-155/'],
        'MT'=>['Montana','Montana recognizes access for service animals and service animals in training with visible identification.',['Service animals and service animals in training may access listed public places without extra charge.','Trainers have the same rights and responsibilities in the cited section.','A service animal in training must wear visible written identification.','Damage liability applies.'],'Montana training access includes visible-identification requirements.','Montana housing access is included, with damage liability.','Montana Code § 49-4-214','https://law.justia.com/codes/montana/title-49/chapter-4/part-2/section-49-4-214/'],
        'NC'=>['North Carolina','North Carolina gives people with disabilities the right to be accompanied by trained service animals and also permits animals in training in listed places when accompanied by a trainer and visibly identified.',['A person with a disability may be accompanied by a service animal trained for the person’s specific disability.','North Carolina references a state service-animal registration tag or proof that the animal is trained or being trained.','Animals in training may enter listed places when accompanied by a trainer.','The animal in training must wear a collar and leash, harness, or cape identifying it as in training.'],'North Carolina recognizes service animals in training when accompanied by a trainer and identified by collar/leash, harness, or cape.','State law references leased, rented, or used premises; federal FHA rules may also apply.','NC Gen. Stat. § 168-4.2','https://codes.findlaw.com/nc/chapter-168-persons-with-disabilities/nc-gen-st-sect-168-4-2/'],
        'NE'=>['Nebraska','Nebraska grants public-place and accommodation access for people with disabilities accompanied by service animals and for bona fide trainers with service animals in training.',['Covered places include streets, public facilities, carriers, lodging, accommodations, amusement/resort places, and other invited public places.','People with disabilities may be accompanied by a service animal.','Bona fide trainers have access with animals in training.','Damage liability applies.'],'Nebraska training access applies to bona fide trainers in listed public places.','Nebraska housing law includes service-animal access and bars extra deposits, with damage liability.','Nebraska Revised Statutes §§ 20-127 and 20-131.04','https://nebraskalegislature.gov/laws/statutes.php?statute=20-127'],
        'NM'=>['New Mexico','New Mexico requires admission for people with disabilities using qualified service animals in buildings open to the public, public accommodations, and common carriers when controlled by an owner, trainer, or handler.',['Access covers public buildings, public accommodations, and common carriers.','The qualified service animal must be controlled by an owner, trainer, or handler.','No-pets policies cannot be used to deny entry to a qualifying animal.','Interference with qualified service animals is separately prohibited.'],'New Mexico references control by an owner, trainer, or handler; verify specific in-training scenarios by setting.','Housing may involve New Mexico law plus federal FHA rules.','New Mexico Statutes §§ 28-11-3 and 28-11-5','https://law.justia.com/codes/new-mexico/chapter-28/article-11/section-28-11-3/'],
        'NV'=>['Nevada','Nevada recognizes service animals and service animals in training in public accommodations and bars extra fees, deposits, or proof demands.',['Refusal of admittance or service because of a service animal is barred.','Refusal because a person is training a service animal is also barred.','Additional fees or deposits are barred.','Questions may cover whether the animal is a service animal/in training and what tasks it performs or is being trained to perform.'],'Nevada expressly recognizes service animals in training in public-accommodation access.','Nevada housing language includes service animals and service animals in training, with damage liability in applicable circumstances.','Nevada NRS Chapter 426 service-animal provisions','https://www.leg.state.nv.us/statutes/73rd/Stats200507.html'],
        'OK'=>['Oklahoma','Oklahoma public-accommodation law uses federal ADA definitions, excludes emotional support and therapy animals from service-animal status, and requires ADA-compliant inquiry limits.',['Oklahoma uses 28 C.F.R. § 36.104 definitions.','Emotional support and therapy animals are excluded from service-animal status in the cited section.','Qualification questions must comply with federal ADA limits.','Oklahoma has misrepresentation language in the cited source.'],'A broad Oklahoma service-animal-in-training public-access right was not confirmed in the reviewed public-accommodation section.','Oklahoma has separate assistance-animal housing accommodation language.','Oklahoma Statutes Title 4 § 801 and Title 41 § 113.2','https://law.justia.com/codes/oklahoma/title-4/section-4-801/'],
        'OR'=>['Oregon','Oregon uses assistance-animal and assistance-animal-trainee language for public accommodations and access to state government services, programs, or activities.',['Oregon defines assistance animal trainee as an animal training for disability-related work or tasks.','Public accommodations and state government services are covered.','Asking about the nature or extent of disability is barred.','Documentation proving trainee status cannot be required.'],'Oregon provides specific access language for assistance animal trainees and trainers.','Housing may involve Oregon rules plus federal FHA rules.','ORS 659A.143 Assistance animals','https://oregon.public.law/statutes/ors_659A.143'],
        'SC'=>['South Carolina','South Carolina law recognizes service animals and service-animals-in-training and allows public accommodations to regulate nonservice animals, including emotional support animals.',['Service animals must be trained to assist or accommodate a sensory, mental, or physical disability.','Emotional support, well-being, comfort, or companionship alone does not constitute service-animal work or tasks.','State materials recognize service-animals-in-training.','No vest, marking, or documentation is required for a trained service animal under the summarized state materials.'],'South Carolina recognizes service-animals-in-training, but handlers should verify setting-specific details and control requirements.','Housing may involve South Carolina fair-housing law plus federal FHA rules.','South Carolina Act No. 44 / Code § 47-3-990 notes','https://law.justia.com/codes/south-carolina/2019/title-47/chapter-3/section-47-3-990/'],
        'SD'=>['South Dakota','South Dakota Human Rights materials and statutes protect service-animal access and specifically allow service animal trainers with identified service animals in training in listed public places.',['Businesses serving the public must allow people with disabilities to bring service animals into customer areas.','A service animal trainer may be accompanied by a service animal in training in listed places.','The animal in training must wear a collar and leash, harness, or cape identifying it as in training.','Extra charges are barred, but damage liability applies.'],'South Dakota recognizes service animals in training when accompanied by a trainer and properly identified.', 'South Dakota housing law and human-rights guidance protect service animals in housing, with documentation rules in some accommodation contexts.', 'South Dakota Codified Laws § 20-13-23.2','https://law.justia.com/codes/south-dakota/title-20/chapter-13/section-20-13-23-2/'],
        'TN'=>['Tennessee','Tennessee service-animal law defines service animals to include animals individually trained or being trained by an employee or puppy raiser from a recognized training agency or school for disability-related work or tasks.',['The state definition includes animals individually trained for disability-related work or tasks.','It also includes animals being trained by an employee or puppy raiser from a recognized training agency or school.','Other species not specified are not service animals for this definition.','Tennessee has misrepresentation penalties for public-accommodation and housing-related false claims.'],'Tennessee training recognition is tied to recognized training agencies or schools in the reviewed statute.', 'Tennessee has housing-related service/support animal misrepresentation language and separate rental-property rules.', 'Tennessee Code §§ 39-14-216 and 39-16-304','https://law.justia.com/codes/tennessee/title-39/chapter-14/part-2/section-39-14-216/'],
        'TX'=>['Texas','Texas guidance protects trained service-animal access and recognizes service animals in training when accompanied by an approved trainer.',['Trained service animals are protected in public places.','A service animal in training must not be denied admittance when accompanied by an approved trainer.','Texas limits demands or inquiries about qualifications or certifications.','When disability is not apparent, Texas guidance lists the ADA-style two questions.'],'Texas training access depends on accompaniment by an approved trainer.','Texas housing may involve state and federal fair-housing rules.','Texas Governor’s Office — Service Animals','https://gov.texas.gov/organization/disabilities/assistance_animals'],
        'UT'=>['Utah','Utah gives people with disabilities the right to be accompanied by a service animal in listed public places and gives access rights to individuals training service animals.',['Public-access rights are recognized for people with disabilities accompanied by service animals.','Individuals training animals to become service animals also have access rights.','Reasonable repair costs for damage may be recovered.','Exclusion remains possible where federal law permits.'],'Utah training access is broader than the federal ADA baseline, subject to behavior/control and covered-place rules.','Utah housing language bars extra fees/deposits for service/support animals, while allowing damage recovery.','Utah Code § 26B-6-803','https://le.utah.gov/xcode/Title26B/Chapter6/C26B-6-S803_2023050320230503.pdf'],
        'VA'=>['Virginia','Virginia defines service dogs by task work for mobility-impaired or otherwise disabled people and extends public-place/public-accommodation rights to certain dogs in training that are at least six months old and appropriately identified.',['Virginia service-dog work or tasks must be directly related to disability or disorder.','Emotional support, well-being, comfort, or companionship alone is not service-dog work.','Dogs in training at least six months old may be covered when handled by experienced trainers, recognized organizations, or certain continuing-training teams.','Virginia specifies identification gear such as harnesses, blaze orange leashes, vests, backpacks, or organization jackets depending on dog type/training status.'],'Virginia recognizes certain dogs in training at least six months old when handler/trainer and identification conditions are met.','Housing may involve Virginia fair-housing rules plus federal FHA accommodation rules.','Virginia Code §§ 51.5-40.1 and 51.5-44','https://law.lis.virginia.gov/vacode/title51.5/chapter9/section51.5-44/'],
        'WA'=>['Washington','Washington public-accommodation resources recognize trained service animals and note expansion to service animals in training.',['Washington public-accommodation guidance covers trained dog guides and service animals.','State materials note expansion to service animals in training.','Some public resources state documentation is not required in public accommodation spaces.','Employment settings can differ from public-accommodation settings.'],'Washington service-animal-in-training access appears broader in public-accommodation spaces, with separate rules for employment.', 'Housing may involve Washington and federal fair-housing rules.', 'Washington State Human Rights Commission — Service Animals','https://www.hum.wa.gov/public-accommodation-pa/use-trained-service-animal-pa'],
        'WV'=>['West Virginia','West Virginia White Cane Law gives blind people and people with disabilities equal use of public facilities and accommodations and includes service-animal and trainer access language.',['Covered places include public buildings, public facilities, public places, public transportation, lodging, restaurants, hospitals, professional offices, and other places open to the public.','People with disabilities are entitled to full and equal accommodations and privileges in covered places.','The statute title and source include service animals and trainers.','Federal ADA rules still control documentation and two-question limits in ADA-covered public accommodations.'],'West Virginia includes service-animal and trainer language in its White Cane Law; verify specific in-training facts against the current statute and setting.','West Virginia assistance-animal housing regulations address reasonable accommodations, fees/deposits, direct threat, and damage liability.', 'West Virginia Code § 5-15-4','https://code.wvlegislature.gov/5-15-4/'],
        'WY'=>['Wyoming','Wyoming protects equal access to public places and defines service animal by reference to federal ADA regulations, including dogs being trained for disability-related tasks.',['Wyoming protects public buildings, public facilities, public places, and public accommodations.','Wyoming uses federal ADA service-animal definitions and includes miniature horses under cited federal regulations.','The definition includes a dog being trained for disability-related work or tasks.','Residential-property language references assistance animals and FHA treatment.'],'Wyoming includes dogs in training within its service-animal definition, subject to covered setting and behavior/control rules.','Wyoming housing language references assistance animals and federal FHA treatment, with damage liability.','Wyoming Statutes §§ 35-13-201 and 35-13-205','https://law.justia.com/codes/wyoming/title-35/chapter-13/article-2/section-35-13-205/'],
    ];

    foreach ($reviewed as $code => $p) $profiles[$code] = adaReviewedStateProfile($code, $p[0], $p[1], $p[2], $p[3], $p[4], $p[5], $p[6]);
    return $profiles;
}
