<?php
declare(strict_types=1);

function gpBetaQaChecklistItems(): array
{
    return [
        [
            'id' => 'deploy_and_config',
            'title' => 'Deploy, Render, and Environment',
            'description' => 'Confirm the beta environment is on the right service/database plans and required env vars are still present.',
            'items' => [
                ['id' => 'render_deploy_complete', 'text' => 'Render redeploy completed successfully after latest GitHub commits.', 'expected' => 'beta.guidepaw.app loads without application error.'],
                ['id' => 'render_web_starter', 'text' => 'Render web service plan is Starter.', 'expected' => 'render.yaml and Render dashboard show the web service on starter.'],
                ['id' => 'render_db_basic', 'text' => 'Render PostgreSQL database plan is still basic-256mb, not starter.', 'expected' => 'Database plan has not been accidentally downgraded or changed.'],
                ['id' => 'robots_txt', 'text' => 'robots.txt is present for search engines.', 'expected' => 'robots.txt lists internal disallows and points at the sitemap.'],
                ['id' => 'sitemap_xml', 'text' => 'sitemap.xml endpoint loads for search engines.', 'expected' => 'sitemap.php returns XML with public GuidePaw URLs.'],
                ['id' => 'ga4_public_home', 'text' => 'Public home page includes the configured GA4 tag when a measurement id is present.', 'expected' => 'The public landing page outputs the gtag snippet for the configured measurement id.'],
                ['id' => 'public_breed_comparison_page', 'text' => 'Public breed comparison page loads and answers a real breed query.', 'expected' => 'breed_comparison.php compares Cavalier King Charles Spaniel vs English Toy Spaniel and links back into the questionnaire.'],
                ['id' => 'public_breed_comparison_hub', 'text' => 'Public breed comparison hub loads.', 'expected' => 'breed_comparison_hub.php opens and lists the comparison set.'],
                ['id' => 'public_breed_family_guide', 'text' => 'Public breed family guide loads.', 'expected' => 'breed_family_guide.php opens and gives a family-level overview before exact comparisons.'],
                ['id' => 'public_breed_comparison_labrador_golden', 'text' => 'Public Labrador vs Golden comparison page loads.', 'expected' => 'breed_compare_labrador_golden.php opens and compares retriever family fit.'],
                ['id' => 'public_breed_comparison_poodle_sizes', 'text' => 'Public Standard vs Toy Poodle comparison page loads.', 'expected' => 'breed_compare_standard_toy_poodle.php opens and explains the poodle size split.'],
                ['id' => 'public_breed_comparison_aussie_mini', 'text' => 'Public Australian Shepherd vs Miniature American Shepherd page loads.', 'expected' => 'breed_compare_aussie_mini_american_shepherd.php opens and compares the herding size split.'],
                ['id' => 'public_breed_comparison_corgi', 'text' => 'Public Pembroke vs Cardigan Corgi comparison page loads.', 'expected' => 'breed_compare_pembroke_cardigan_corgi.php opens and compares the corgi families.'],
                ['id' => 'public_breed_comparison_frenchie_boston', 'text' => 'Public French Bulldog vs Boston Terrier comparison page loads.', 'expected' => 'breed_compare_french_bulldog_boston_terrier.php opens and compares the compact companion breeds.'],
                ['id' => 'public_faq_page', 'text' => 'Public FAQ page loads and answers common GuidePaw questions.', 'expected' => 'faq.php opens with public FAQ content about breed research, support, and public profiles.'],
                ['id' => 'public_service_dog_esa_legal_info_page', 'text' => 'Public service dog and ESA legal info page loads.', 'expected' => 'service_dog_esa_legal_info.php opens with the public legal summary and official links.'],
                ['id' => 'public_housing_access_faq_page', 'text' => 'Public housing and access FAQ page loads.', 'expected' => 'housing_access_faq.php opens with the public housing and access dispute summary.'],
                ['id' => 'zepto_env_present', 'text' => 'ZeptoMail environment variables are present.', 'expected' => 'ZEPTO_API_URL, token, from address/name, bounce address, and MAIL_FROM values exist.'],
                ['id' => 'telegram_env_present', 'text' => 'Telegram beta notification env vars are present if Telegram notifications are enabled.', 'expected' => 'Telegram bot token/chat id settings remain configured outside committed code.'],
                ['id' => 'migrations_applied', 'text' => 'Database migrations run successfully.', 'expected' => 'Dog access/status/transfer/audit tables and columns exist on beta.'],
            ],
        ],
        [
            'id' => 'login_and_required_profile',
            'title' => 'Login and Required Handler Profile',
            'description' => 'Validate the required handler profile gate and contact defaults.',
            'items' => [
                ['id' => 'login_page', 'text' => 'Login page loads.', 'expected' => 'login.php opens with the handler login form.'],
                ['id' => 'login_breed_questionnaire_cta', 'text' => 'Login page surfaces the public breed questionnaire CTA.', 'expected' => 'The login page invites visitors to open the Breed Questionnaire without an account.'],
                ['id' => 'public_home_page', 'text' => 'Public home landing page loads for logged-out visitors.', 'expected' => 'index.php shows the public GuidePaw landing page before sign in.'],
                ['id' => 'login_admin', 'text' => 'Admin account can log in.', 'expected' => 'Admin lands on dashboard or required Handler Profile page if missing required fields.'],
                ['id' => 'login_test_acct', 'text' => 'Test account can log in.', 'expected' => 'Test account can proceed after required fields are present.'],
                ['id' => 'required_profile_gate', 'text' => 'Incomplete account is redirected to Handler Profile before continuing.', 'expected' => 'Display name, Home street, Home city, Home state, Home ZIP, Public phone, and Public email are blocking fields.'],
                ['id' => 'home_address_required', 'text' => 'Structured home address is required on registration and Handler Profile.', 'expected' => 'Street, apartment, city, state, and ZIP save separately and are inherited by dog profile defaults.'],
                ['id' => 'home_state_optional', 'text' => 'Home state is part of the required address fields on Handler Profile and registration.', 'expected' => 'State code saves and is available as the ADA card fallback.'],
                ['id' => 'backup_optional', 'text' => 'Backup contact name/phone can be left blank.', 'expected' => 'User can save and continue without backup contact info.'],
                ['id' => 'return_after_save', 'text' => 'Required profile save returns user to the originally requested page.', 'expected' => 'Save and Continue redirects correctly.'],
                ['id' => 'beta_token_page', 'text' => 'Beta Token page loads for approved access.', 'expected' => 'beta_token.php opens and can continue to account creation.'],
                ['id' => 'register_page', 'text' => 'Register page loads for new handlers.', 'expected' => 'register.php opens or routes through beta token and shows required name, street, city, state, ZIP, email, phone, and password fields.'],
                ['id' => 'reset_password_page', 'text' => 'Password recovery page loads with confirm password support.', 'expected' => 'reset_password.php opens and shows password visibility plus confirmation before saving.'],
                ['id' => 'setup_2fa_page', 'text' => 'Setup 2FA page loads for logged-in handlers.', 'expected' => 'setup_2fa.php opens and shows the TOTP secret, scan QR code, and verification form.'],
                ['id' => 'verify_2fa_redirect', 'text' => 'Verify 2FA page stays protected outside a pending login flow.', 'expected' => 'verify_2fa.php redirects to login when no 2FA session is pending.'],
                ['id' => 'logout_redirect', 'text' => 'Logout page redirects to Login.', 'expected' => 'logout.php clears the session and routes back to login.php.'],
                ['id' => 'profile_completion_report', 'text' => 'Admin profile completion report loads.', 'expected' => 'admin_profile_completion.php shows total, complete, missing required, and optional backup counts.'],
            ],
        ],
        [
            'id' => 'handler_profile_and_images',
            'title' => 'Handler Profile and Images',
            'description' => 'Confirm handler profile defaults, cropped images, and persistence after redeploy/reload.',
            'items' => [
                ['id' => 'handler_profile_save', 'text' => 'Handler Profile saves display name, structured home address, phone, public email, home state, optional backup, notes.', 'expected' => 'Saved values reload correctly and the address parts carry through to dog defaults.'],
                ['id' => 'handler_support_badge', 'text' => 'Handler Profile shows the current support badge art and status for funded or lifetime accounts.', 'expected' => 'The active badge image and label display on the handler profile without breaking the save form.'],
                ['id' => 'handler_photo_upload', 'text' => 'Upload/crop/save handler profile picture.', 'expected' => 'Preview updates and save succeeds.'],
                ['id' => 'handler_photo_persists', 'text' => 'Handler profile picture persists after logout/login and page refresh.', 'expected' => 'Image still displays because new photos are stored in database.'],
                ['id' => 'handler_defaults_inherited', 'text' => 'Handler defaults are inherited by dog QR/public profile.', 'expected' => 'Dog profile does not require retyping shared handler info.'],
                ['id' => 'dog_profile_support_badge', 'text' => 'Dog Profile shows the support badge on the private profile page.', 'expected' => 'The active badge image and label appear above the QR profile card.'],
                ['id' => 'public_profile_support_badge', 'text' => 'Public QR profile shows the support badge.', 'expected' => 'Visitors can see the badge on the public profile without opening admin pages.'],
            ],
        ],
        [
            'id' => 'manage_dogs_active_profile',
            'title' => 'Manage Dogs and Active Profile',
            'description' => 'Confirm one-dog default behavior, active profile visibility, and collapsed add-dog behavior.',
            'items' => [
                ['id' => 'one_dog_default_active', 'text' => 'Account with one dog defaults that dog as active.', 'expected' => 'Dashboard and Manage Dogs show that dog as the active profile.'],
                ['id' => 'active_dog_visibility', 'text' => 'Active dog is visually obvious on Manage Dogs.', 'expected' => 'Dog name is larger, row highlighted, badge says Active Profile, note says GuidePaw is using it.'],
                ['id' => 'add_dog_open_first', 'text' => 'Add Dog form is open when account has no dogs.', 'expected' => 'New handlers can immediately add first dog.'],
                ['id' => 'add_another_collapsed', 'text' => 'Add Another Dog form is collapsed after at least one dog exists.', 'expected' => 'Button opens/closes the form.'],
                ['id' => 'switch_active_dog', 'text' => 'Switch active dog with Use button.', 'expected' => 'Dashboard and active highlights update.'],
                ['id' => 'manage_dogs_badges', 'text' => 'Manage Dogs badges display ownership/access context.', 'expected' => 'Owner/shared/editor/viewer/status badges appear correctly.'],
                ['id' => 'access_audit_buttons', 'text' => 'Access and Audit buttons appear on dog rows.', 'expected' => 'Buttons open dog_access.php and dog_access_audit.php for that dog.'],
            ],
        ],
        [
            'id' => 'dog_profile_qr_found_flow',
            'title' => 'Dog Profile, QR, and Found-Dog Flow',
            'description' => 'Validate QR profile inheritance and found-dog contact/report workflow.',
            'items' => [
                ['id' => 'dog_profile_loads', 'text' => 'Dog Profile page loads for active dog.', 'expected' => 'No application error.'],
                ['id' => 'dog_profile_address_fields', 'text' => 'Dog Profile handler address uses separate street, apt, city, state, and ZIP fields.', 'expected' => 'The dog profile handler override shows split address inputs instead of one freeform line.'],
                ['id' => 'dog_profile_age_auto_fill', 'text' => 'Dog Profile auto-fills approximate age when birthday is set and allows manual age when birthday is blank.', 'expected' => 'The age field explains the rule and becomes read-only when a birthday is present.'],
                ['id' => 'dog_add_age_auto_fill', 'text' => 'Add Dog form auto-fills approximate age when birthday is set and allows manual age when birthday is blank.', 'expected' => 'The add-dog form explains the rule and keeps the age field manual only when no birthday is entered.'],
                ['id' => 'qr_profile_loads', 'text' => 'Public QR profile opens with valid dog/token link.', 'expected' => 'Public page shows dog identity and inherited handler contact defaults.'],
                ['id' => 'qr_tracking_loads', 'text' => 'QR Tracking page loads for the active dog or shows the add-on notice when that dog is not covered yet.', 'expected' => 'Tracking page shows QR opens and recent scan activity, or the per-dog add-on notice.'],
                ['id' => 'qr_invalid_token', 'text' => 'Invalid or missing QR token is rejected.', 'expected' => 'Public page returns a not-found style response, not private data.'],
                ['id' => 'found_location_report', 'text' => 'Found Location form submits successfully.', 'expected' => 'Report is saved and handler/admin notifications are triggered.'],
                ['id' => 'found_report_admin', 'text' => 'Admin found-dog reports page shows submitted report.', 'expected' => 'admin_found_dog_reports.php lists the report details.'],
                ['id' => 'contact_fallback_order', 'text' => 'Public contact fallback order works.', 'expected' => 'Dog-specific public fields override Handler Profile, which overrides owner/account fallback.'],
            ],
        ],
        [
            'id' => 'notifications',
            'title' => 'Notifications',
            'description' => 'Validate beta request, admin, dog access, and transfer notifications.',
            'items' => [
                ['id' => 'beta_request_email', 'text' => 'Submit beta access request and confirm admin email notification.', 'expected' => 'Admin notification email arrives.'],
                ['id' => 'beta_request_telegram', 'text' => 'Submit beta access request and confirm Telegram notification if enabled.', 'expected' => 'Telegram bot receives beta request alert.'],
                ['id' => 'admin_notification_test', 'text' => 'Admin Notification Test page sends email/Telegram test.', 'expected' => 'Test succeeds and messages arrive.'],
                ['id' => 'dog_access_email', 'text' => 'Invite co-op/shared dog access and confirm email notification.', 'expected' => 'Recipient receives a pending GuidePaw dog access invite email.'],
                ['id' => 'transfer_request_email', 'text' => 'Send dog ownership transfer request and confirm recipient email.', 'expected' => 'Receiving handler gets transfer request email.'],
                ['id' => 'transfer_result_email', 'text' => 'Accept/decline transfer and confirm original owner email.', 'expected' => 'Original owner receives accepted/declined result email.'],
                ['id' => 'email_failure_safe', 'text' => 'Confirm actions complete even if notification send fails.', 'expected' => 'Access/transfer action succeeds and failure is logged instead of blocking workflow.'],
            ],
        ],
        [
            'id' => 'ada_access_card',
            'title' => 'ADA Access Card and Legal Notes',
            'description' => 'Validate ADA/public-access card behavior and service dog law references.',
            'items' => [
                ['id' => 'ada_card_loads', 'text' => 'ADA Access Card page loads.', 'expected' => 'No app error and correct active dog/handler information displays.'],
                ['id' => 'ada_button_name', 'text' => 'Button and labels use ADA Access Card language.', 'expected' => 'No old wallet/bank-account wording remains.'],
                ['id' => 'lock_screen_focus', 'text' => 'Lock screen mode focuses display on card content.', 'expected' => 'Screen is visually locked down to the access card content.'],
                ['id' => 'state_law_detection', 'text' => 'State/legal notes behavior checked.', 'expected' => 'If implemented, GPS/state-specific service dog info is accurate; if not, roadmap note remains.'],
                ['id' => 'ada_notes_page', 'text' => 'Detailed ADA Notes page loads from menu.', 'expected' => 'service_dog_rights.php opens correctly.'],
                ['id' => 'air_travel_rights', 'text' => 'Air Travel Rights page loads and distinguishes service dogs from service dogs in training.', 'expected' => 'air_travel_rights.php opens and shows flight guidance for service dogs plus SDIT limitations.'],
                ['id' => 'air_travel_dashboard', 'text' => 'Dashboard exposes Air Travel as a Today shortcut.', 'expected' => 'index.php shows a direct Air Travel tile alongside the other fast actions.'],
            ],
        ],
        [
            'id' => 'dog_access_status_transfer',
            'title' => 'Dog Access, Co-op, Status, and Transfer',
            'description' => 'Full workflow for co-op handlers, temporary access, retirement/archive, and transfer requests.',
            'items' => [
                ['id' => 'dog_list_archive_split', 'text' => 'Manage Dogs separates active and archived dogs.', 'expected' => 'Archived dogs stay in a dedicated archive section instead of the main working list.'],
                ['id' => 'dog_access_page_loads', 'text' => 'Dog Access & Status page loads from Manage Dogs.', 'expected' => 'dog_access.php opens for selected dog.'],
                ['id' => 'grant_view_access', 'text' => 'Owner invites Viewer access to another GuidePaw account.', 'expected' => 'Recipient sees a pending invite and can accept it before the dog appears in shared/viewer access.'],
                ['id' => 'grant_editor_access', 'text' => 'Owner invites Contributor/Editor access.', 'expected' => 'Recipient sees a pending invite and can accept it before editing allowed dog areas.'],
                ['id' => 'collaboration_page', 'text' => 'Handler Collaboration page loads for the active dog.', 'expected' => 'collaboration.php opens and shows handshake-based sharing tools for the current active dog.'],
                ['id' => 'temporary_access_end_date', 'text' => 'Owner sets temporary access end date.', 'expected' => 'End date saves and displays.'],
                ['id' => 'expired_access_cleanup', 'text' => 'Expired access is cleaned up after end date.', 'expected' => 'Dashboard, Manage Dogs, Dog Access, or Audit page marks old access expired and refreshes once.'],
                ['id' => 'revoke_access', 'text' => 'Owner revokes shared handler access.', 'expected' => 'Shared handler status becomes revoked and dog disappears from their usable list.'],
                ['id' => 'retire_dog', 'text' => 'Mark dog Retired or Archived.', 'expected' => 'Dog history remains, but it does not stay as active working dog.'],
                ['id' => 'reactivate_dog', 'text' => 'Change retired/archived dog back to Active or In training.', 'expected' => 'Dog can be used as active profile again.'],
                ['id' => 'send_transfer', 'text' => 'Owner sends ownership transfer request.', 'expected' => 'Pending request appears for receiving account and dashboard alert shows.'],
                ['id' => 'accept_transfer', 'text' => 'Receiving handler accepts transfer.', 'expected' => 'Owner changes, dog history stays attached, optional previous-owner editor access behaves correctly.'],
                ['id' => 'decline_transfer', 'text' => 'Receiving handler declines transfer.', 'expected' => 'Ownership does not change and original owner is notified.'],
            ],
        ],
        [
            'id' => 'dashboard_and_audit',
            'title' => 'Dashboard and Audit Trail',
            'description' => 'Confirm dashboard alerts, attention counts, and audit timeline events.',
            'items' => [
                ['id' => 'dashboard_transfer_alert', 'text' => 'Dashboard shows pending dog transfer alert.', 'expected' => 'Pending Dog Transfer card appears with Review Now.'],
                ['id' => 'attention_count', 'text' => 'Needs Attention count includes transfer requests.', 'expected' => 'Count increases when transfer request is pending.'],
                ['id' => 'audit_page_loads', 'text' => 'Dog Audit Timeline page loads.', 'expected' => 'dog_access_audit.php opens and shows dog info.'],
                ['id' => 'audit_status_event', 'text' => 'Status changes appear in audit timeline.', 'expected' => 'Retired/active changes are logged.'],
                ['id' => 'audit_access_event', 'text' => 'Shared access add/change/revoke appears in audit timeline.', 'expected' => 'Audit page shows access event with before/after values when available.'],
                ['id' => 'audit_transfer_event', 'text' => 'Transfer request/accept/decline appears in audit timeline.', 'expected' => 'Audit page shows transfer lifecycle.'],
            ],
        ],
        [
            'id' => 'training_logs_and_care',
            'title' => 'Logs, Training, and Care',
            'description' => 'Smoke-test core handler features after access/status changes.',
            'items' => [
                ['id' => 'quick_session', 'text' => 'Quick Session works for active dog.', 'expected' => 'Session saves and appears in history.'],
                ['id' => 'daily_win', 'text' => 'Home page shows a daily quick win checkbox that saves as a training log.', 'expected' => 'Today page displays one quick-win prompt, accepts completion, and records a log entry.'],
                ['id' => 'detailed_log', 'text' => 'Detailed Log works for active dog if feature enabled.', 'expected' => 'Log saves with selected values.'],
                ['id' => 'settings_page', 'text' => 'Settings page loads and stays focused on account controls.', 'expected' => 'User can review password, logout, and app settings without the redundant handler profile shortcut.'],
                ['id' => 'plans_page', 'text' => 'Plans & Access page loads and shows the current plan comparison plus add-on services.', 'expected' => 'User can review Free, Plus, and Pro cards, a la carte services, and understand what is locked on each plan.'],
                ['id' => 'service_purchase_page', 'text' => 'A la carte service purchase page loads from Plans & Access.', 'expected' => 'User can open a specific add-on purchase page, see the selected service, and continue to Stripe or a dog selector when required.'],
                ['id' => 'contact_us_page', 'text' => 'Contact Us page loads and surfaces the official GuidePaw Facebook social link.', 'expected' => 'User can open the contact page and see the GuidePaw Facebook link plus the saved profile link when present.'],
                ['id' => 'profile_page', 'text' => 'Dog Profile page loads and shows dog details.', 'expected' => 'User can review owner details, microchip, and edit profile controls.'],
                ['id' => 'edit_profile_page', 'text' => 'Edit Dog Profile page loads.', 'expected' => 'edit_profile.php opens for the active dog without application error.'],
                ['id' => 'manage_dogs_redirect', 'text' => 'Manage Dogs redirect still lands on Dogs page.', 'expected' => 'manage_dogs.php routes to dogs.php with the original query string.'],
                ['id' => 'quick_log_page', 'text' => 'Quick Log page loads and shows the fast session form.', 'expected' => 'User can start a quick session and save it from the fast entry page.'],
                ['id' => 'log_entry_page', 'text' => 'Training Log entry page loads and shows camera capture controls.', 'expected' => 'User can log training details, open the camera for photo or video capture, and save the record.'],
                ['id' => 'view_logs_page', 'text' => 'View Logs page loads and shows training history.', 'expected' => 'User can review prior logs and queued offline entries.'],
                ['id' => 'edit_log_page', 'text' => 'Edit Training Log page loads from history.', 'expected' => 'edit_log.php opens with GPS update controls, manual coordinates, environment, focus, skills, and notes fields.'],
                ['id' => 'update_log_guard', 'text' => 'Update Log only accepts POST and returns to history.', 'expected' => 'update_log.php redirects to view_logs.php when opened directly.'],
                ['id' => 'media_review', 'text' => 'Media Review page opens for logs with image/video/audio attachments.', 'expected' => 'User can rate camera stability, audio clarity, and training value.'],
                ['id' => 'video_review', 'text' => 'Video Review page opens for checkpoint video logs.', 'expected' => 'User can review clip quality, audio, and checkpoint readiness.'],
                ['id' => 'coach_review', 'text' => 'Coach Review page opens and lets you queue regression items for follow-up.', 'expected' => 'Open training regressions can be promoted into a coach review queue and updated.'],
                ['id' => 'regression_engine', 'text' => 'Regression Engine page opens and shows reset plans for open regressions.', 'expected' => 'User can review open regression events and save a reset plan update.'],
                ['id' => 'history_loads', 'text' => 'History page loads and filters active dog data correctly.', 'expected' => 'No stale/retired dog confusion unless intentionally viewing history.'],
                ['id' => 'training_program', 'text' => 'Training Program page loads with collapsible helper panels and bundle buttons.', 'expected' => 'Active dog training ladder/profile works, the extra panels stay collapsed, and the page surfaces AKC bundle buttons that load the matching training pieces.'],
                ['id' => 'training_suggestions_links', 'text' => 'Training suggestions include direct Start module links.', 'expected' => 'training_program.php shows clickable links from coaching suggestions into the relevant module pages.'],
                ['id' => 'training_command_words_editor', 'text' => 'Training Program page lets the user edit command words.', 'expected' => 'Active dog training ladder/profile works and the command-word editor shows default cues with a save action.'],
                ['id' => 'goal_intake_page', 'text' => 'Goal Intake page loads.', 'expected' => 'training_goal_intake.php opens and can create or archive goals.'],
                ['id' => 'habit_repair_page', 'text' => 'Habit Repair page loads.', 'expected' => 'habit_repair.php opens and shows repair protocols.'],
                ['id' => 'behavior_risk_scoring', 'text' => 'Behavior Risk Scoring page loads and summarizes the current risk picture.', 'expected' => 'User can inspect risk bands, incident reasons, and next-step recommendations.'],
                ['id' => 'goal_builder', 'text' => 'Goal Builder page loads, saves a generated goal, and shows a recommended path.', 'expected' => 'User can draft a measurable goal, see suggested next modules, and persist it to training goals.'],
                ['id' => 'training_session_log', 'text' => 'Training Session Log page loads and saves a session.', 'expected' => 'User can log reps and see a session status result.'],
                ['id' => 'training_command_words_reference', 'text' => 'Training Session Log page keeps a command-word reference for the active dog.', 'expected' => 'Session log page surfaces the read-only command word cues that help handlers keep the same language during training.'],
                ['id' => 'training_history', 'text' => 'Training History page loads and lists records.', 'expected' => 'Active and archived training records remain visible.'],
                ['id' => 'training_history_export', 'text' => 'Training History export downloads CSV.', 'expected' => 'training_history_export.php returns a CSV export for the selected status.'],
                ['id' => 'backup_import_redirect', 'text' => 'Backup import redirects to Backup Tools when opened directly.', 'expected' => 'import_backup.php sends browser back to backup.php unless posted with a file.'],
                ['id' => 'save_log_method_guard', 'text' => 'Save Log guards against non-POST access.', 'expected' => 'save_log.php rejects GET requests with a clear method-not-allowed response.'],
                ['id' => 'update_log_redirect', 'text' => 'Update Log redirects or updates through the history flow.', 'expected' => 'update_log.php only accepts POST and returns user to history.'],
                ['id' => 'stats_page', 'text' => 'Stats page loads and summarizes training progress.', 'expected' => 'User can review logs, focus, and recent trends.'],
                ['id' => 'tactical_training_page', 'text' => 'Tactical Training page loads and shows request or approved access.', 'expected' => 'Unapproved users see the application form while approved users see the readiness path.'],
                ['id' => 'candidate_assessment', 'text' => 'Candidate Assessment page loads if enabled.', 'expected' => 'Assessment can be started or viewed.'],
                ['id' => 'candidate_comparison', 'text' => 'Candidate Comparison page loads if enabled.', 'expected' => 'User can compare multiple dog candidate assessments side by side.'],
                ['id' => 'community_challenges', 'text' => 'Community Challenges page loads if enabled.', 'expected' => 'User can choose a challenge and see the current challenge state.'],
                ['id' => 'trucking_mode', 'text' => 'Trucking Mode page opens for the active dog.', 'expected' => 'User can pick a day type and see the travel-day plan.'],
                ['id' => 'trainer_marketplace', 'text' => 'Trainer Marketplace page loads and free users see the Plus paywall.', 'expected' => 'Plus users can browse saved trainer contacts while free users see the upgrade notice.'],
                ['id' => 'admin_funding_settings', 'text' => 'Admin Funding Settings page loads and shows current support configuration.', 'expected' => 'Admin can review the configured Stripe secret status, price IDs, fallback funding URL, merch URL, and Discord URL.'],
                ['id' => 'vet_appointments', 'text' => 'Vet Appointments page loads and saves reminder.', 'expected' => 'Appointment appears on dashboard reminders.'],
                ['id' => 'medications', 'text' => 'Medications page loads if enabled.', 'expected' => 'Medication reminder/refill behavior remains intact.'],
                ['id' => 'health_docs', 'text' => 'Health Docs page loads if enabled.', 'expected' => 'Documents remain associated with dog profile and saved vets can be searched while adding a contact.'],
                ['id' => 'alerts_page', 'text' => 'Smart Alerts page loads and shows current alerts.', 'expected' => 'User can open alerts and see the current alert list.'],
                ['id' => 'alerts_module_links', 'text' => 'Smart Alerts surfaces module start links when training guidance is shown.', 'expected' => 'alerts.php and the dashboard include Start module links for coaching-style alerts.'],
                ['id' => 'alerts_today', 'text' => 'Dashboard exposes Smart Alerts as a Today shortcut.', 'expected' => 'index.php shows a direct Smart Alerts tile.'],
                ['id' => 'community_page', 'text' => 'Community page loads and shows merch, Discord, and forum entry points.', 'expected' => 'User can open the hub and see the swag store, Discord join link, and forum shortcut.'],
                ['id' => 'support_funding_page', 'text' => 'Support Funding page loads and shows one-time or monthly support actions.', 'expected' => 'User can open the support page, see the checkout buttons or fallback message, and find links to merch or community.'],
                ['id' => 'stripe_webhook_endpoint', 'text' => 'Stripe webhook endpoint accepts POST-only events for completed support checkouts.', 'expected' => 'stripe_webhook.php returns 405 for GET and accepts signed POST requests for checkout.session.completed.'],
                ['id' => 'business_costs_page', 'text' => 'Business Costs page loads and shows current operating costs plus future expansion estimates.', 'expected' => 'Admin can review live support revenue versus current and planned cost items, then edit the ledger in app.'],
                ['id' => 'forum_page', 'text' => 'Forum page loads and shows thread roles, support badges, and search.', 'expected' => 'User can create a discussion thread, post a reply, and see creator role and badge context in the thread list and thread view.'],
                ['id' => 'forum_moderation_controls', 'text' => 'Forum moderation controls are available to admins and moderators.', 'expected' => 'Admin or moderator can open the collapsed thread tools to pin, unpin, close, reopen, archive, restore, or delete threads and delete replies from the thread view.'],
                ['id' => 'forum_archive_review', 'text' => 'Forum archive review section is available to admins.', 'expected' => 'Admin can review archived threads in a dedicated archive section and restore or delete them from there.'],
                ['id' => 'today_core_actions', 'text' => 'Dashboard Today card stays focused on core actions.', 'expected' => 'Quick Session, Detailed Log, Training Plan, ADA Access, and Alerts are present; extras are moved to the menu.'],
                ['id' => 'today_pruned', 'text' => 'Dashboard Today card excludes the long tail of tool shortcuts.', 'expected' => 'Health Docs, Appointments, Medications, Wearable Sync, Trucker, Stats, Certification, and similar clutter are not shown there.'],
            ],
        ],
        [
            'id' => 'mobile_pwa_offline',
            'title' => 'Mobile, PWA, and Offline Behavior',
            'description' => 'Validate mobile navigation and browser/PWA behaviors.',
            'items' => [
                ['id' => 'onboarding_walkthrough', 'text' => 'First login opens a setup walkthrough with profile, dog, and dashboard steps.', 'expected' => 'onboarding_setup.php shows the quick setup flow and the finish button returns to the dashboard.'],
                ['id' => 'mobile_menu_groups', 'text' => 'Mobile menu groups open and close correctly.', 'expected' => 'Dog, Logs, Training, Care, and More sections appear as grouped categories with Training extras and Admin tools nested inside More, and Beta QA Checklist lives under Admin tools.'],
                ['id' => 'bottom_nav', 'text' => 'Bottom nav routes work.', 'expected' => 'Home, Log, History, Alerts, Menu open expected pages.'],
                ['id' => 'install_home_screen', 'text' => 'PWA can be installed to home screen.', 'expected' => 'Manifest/icon load and app opens standalone where supported.'],
                ['id' => 'notification_permission', 'text' => 'Enable reminders button prompts for notifications.', 'expected' => 'Browser permission flow works or fails gracefully.'],
                ['id' => 'offline_queue', 'text' => 'Offline queued logs/media sync behavior smoke-tested.', 'expected' => 'Queued count/status display updates and sync button does not error.'],
                ['id' => 'mobile_layout', 'text' => 'Key pages are readable on phone screen.', 'expected' => 'No horizontal scrolling, clipped buttons, or hidden required fields.'],
            ],
        ],
        [
            'id' => 'admin_and_support',
            'title' => 'Admin, Feedback, and Support',
            'description' => 'Validate admin surfaces and bug-report support flow.',
            'items' => [
                ['id' => 'admin_home', 'text' => 'Admin Home loads for admin account.', 'expected' => 'admin.php opens without application error.'],
                ['id' => 'healthz_page', 'text' => 'Health check page reports ok.', 'expected' => 'healthz.php returns a healthy status and database ok.'],
                ['id' => 'csrf_token_page', 'text' => 'CSRF token helper returns a token for logged-in users.', 'expected' => 'csrf_token.php returns success:true and a CSRF token.'],
                ['id' => 'api_login_endpoint', 'text' => 'API login issues a bearer token for the admin account.', 'expected' => 'api/login.php returns success:true and a token.'],
                ['id' => 'api_me_endpoint', 'text' => 'API me endpoint returns the authenticated user.', 'expected' => 'api/me.php returns success:true and the current account details.'],
                ['id' => 'api_dogs_endpoint', 'text' => 'API dogs endpoint returns accessible dogs.', 'expected' => 'api/dogs.php returns success:true and an array of accessible dogs.'],
                ['id' => 'api_logs_endpoint', 'text' => 'API logs endpoint returns log records.', 'expected' => 'api/logs.php returns success:true and a log array.'],
                ['id' => 'api_billing_endpoint', 'text' => 'API billing endpoint returns plan state, support options, and add-on catalog.', 'expected' => 'api/billing.php returns success:true, a current plan summary, support options, and service rows.'],
                ['id' => 'beta_requests_admin', 'text' => 'Beta Requests admin page loads.', 'expected' => 'Submitted beta requests are visible/manageable.'],
                ['id' => 'admin_beta_requests', 'text' => 'Admin Beta Access Requests page loads.', 'expected' => 'admin_beta_requests.php lists requests and access controls.'],
                ['id' => 'admin_tactical_requests', 'text' => 'Admin Tactical Requests page loads and can approve or deny verified teams.', 'expected' => 'admin_tactical_requests.php lists tactical requests and lets admin approve or deny them.'],
                ['id' => 'admin_feature_roadmap', 'text' => 'Admin Feature Roadmap page loads.', 'expected' => 'admin_feature_roadmap.php shows roadmap entries and flag states.'],
                ['id' => 'admin_audit_log', 'text' => 'Admin Audit Log page loads.', 'expected' => 'admin_audit_log.php shows audit entries and filters.'],
                ['id' => 'admin_smtp_audit', 'text' => 'Admin SMTP Audit page loads.', 'expected' => 'admin_smtp_audit.php reports env and SMTP connection details.'],
                ['id' => 'admin_zeptomail_audit', 'text' => 'Admin ZeptoMail Audit page loads.', 'expected' => 'admin_zeptomail_audit.php reports env and API connectivity.'],
                ['id' => 'feedback_auto_context', 'text' => 'Feedback/Bug Report page captures relevant troubleshooting context.', 'expected' => 'Report includes page/error/account context where available.'],
                ['id' => 'feedback_category_picker', 'text' => 'Feedback/Bug Report category picker clearly offers Bug, Feature request, and Enhancement.', 'expected' => 'Category choice is visible as a segmented control before the details field.'],
                ['id' => 'breed_questionnaire', 'text' => 'Breed Questionnaire page loads publicly and returns ranked breed ideas.', 'expected' => 'Public questionnaire shows top matches, family guidance, and a no-account-needed path.'],
                ['id' => 'breed_questionnaire_size_labels', 'text' => 'Breed Questionnaire shows approximate weight descriptions for the size categories.', 'expected' => 'Toy, Small, Medium, Large, and Giant size choices include approximate adult weight ranges.'],
                ['id' => 'breed_questionnaire_live_suggestions', 'text' => 'Breed Questionnaire shows live breed-name suggestions while typing.', 'expected' => 'The breed name field includes an autocomplete list, a visible live suggestion pane, and hint text for quick matching.'],
                ['id' => 'breed_questionnaire_focus_filters', 'text' => 'Breed Questionnaire shows quick filters for public access, companion, and task work.', 'expected' => 'The breed name area includes a segmented control with Any, Public access, Companion, and task work buttons.'],
                ['id' => 'breed_questionnaire_advanced_section', 'text' => 'Breed Questionnaire hides the secondary filters behind an Advanced section.', 'expected' => 'Exercise, grooming, public exposure, experience, sensitivity, and drill-down controls live inside a collapsed Advanced disclosure.'],
                ['id' => 'breed_questionnaire_family_browse', 'text' => 'Breed Questionnaire lets handlers browse breeds inside a selected family.', 'expected' => 'A selected family reveals a browse section with more breeds in that family and a button to load a specific breed.'],
                ['id' => 'breed_questionnaire_spaniel_browse', 'text' => 'Breed Questionnaire shows more than the first six spaniel-family breeds.', 'expected' => 'Spaniel Family should reveal American Cocker Spaniel, King Charles Spaniel, and breed buttons that let the handler keep drilling down.'],
                ['id' => 'breed_questionnaire_retriever_browse', 'text' => 'Breed Questionnaire shows more than the first few retriever-family breeds.', 'expected' => 'Retriever Family should reveal Golden Retriever, Labrador Retriever, and breed buttons that let the handler keep drilling down.'],
                ['id' => 'breed_questionnaire_herding_browse', 'text' => 'Breed Questionnaire shows more than the first few herding-family breeds.', 'expected' => 'Herding / Shepherd Family should reveal Border Collie, Pembroke Welsh Corgi, and breed buttons that let the handler keep drilling down.'],
                ['id' => 'breed_questionnaire_focus_ranking', 'text' => 'Breed Questionnaire lets the selected focus bias the ranked results.', 'expected' => 'Selecting Public access should nudge the ranked results toward public-access breeds.'],
                ['id' => 'breed_questionnaire_live_best_for', 'text' => 'Breed Questionnaire shows a short best-for tag in live suggestions.', 'expected' => 'Suggestion cards include a short best-for line like public access, alert work, or broader research.'],
                ['id' => 'breed_questionnaire_toy_alignment', 'text' => 'Breed Questionnaire keeps toy-size requests away from large-breed recommendations.', 'expected' => 'Submitting toy size should surface a toy or small result at the top, not a large breed.'],
                ['id' => 'breed_questionnaire_breed_query', 'text' => 'Breed Questionnaire can prioritize a breed name the user already knows.', 'expected' => 'Typing Cavalier King Charles pulls Cavalier King Charles Spaniel to the top or near the top.'],
                ['id' => 'breed_questionnaire_king_charles_query', 'text' => 'Breed Questionnaire can separate King Charles Spaniel from Cavalier King Charles Spaniel.', 'expected' => 'Typing King Charles should surface English Toy Spaniel, not Cavalier King Charles Spaniel.'],
                ['id' => 'breed_questionnaire_toy_poodle_alias', 'text' => 'Breed Questionnaire recognizes the Toy Poodle alias.', 'expected' => 'Typing Toy Poodle should surface Toy Poodle at the top.'],
                ['id' => 'breed_questionnaire_westie_alias', 'text' => 'Breed Questionnaire recognizes the Westie alias.', 'expected' => 'Typing Westie should surface West Highland White Terrier at the top.'],
                ['id' => 'breed_questionnaire_toy_manchester_alias', 'text' => 'Breed Questionnaire recognizes the Toy Manchester Terrier alias.', 'expected' => 'Typing Toy Manchester Terrier should surface Manchester Terrier (Toy) at the top.'],
                ['id' => 'breed_questionnaire_min_pin_alias', 'text' => 'Breed Questionnaire recognizes the Min Pin alias.', 'expected' => 'Typing Min Pin should surface Miniature Pinscher at the top.'],
                ['id' => 'breed_questionnaire_russian_toy_alias', 'text' => 'Breed Questionnaire recognizes the Russian Toy Terrier alias.', 'expected' => 'Typing Russian Toy Terrier should surface Russian Toy at the top.'],
                ['id' => 'breed_questionnaire_silky_alias', 'text' => 'Breed Questionnaire recognizes the Silky alias.', 'expected' => 'Typing Silky should surface Silky Terrier at the top.'],
                ['id' => 'breed_questionnaire_american_cocker_alias', 'text' => 'Breed Questionnaire recognizes the American Cocker alias.', 'expected' => 'Typing American Cocker should surface American Cocker Spaniel at the top.'],
                ['id' => 'breed_questionnaire_doxie_alias', 'text' => 'Breed Questionnaire recognizes the Doxie alias.', 'expected' => 'Typing Doxie should surface Dachshund at the top.'],
                ['id' => 'breed_questionnaire_pembroke_corgi_alias', 'text' => 'Breed Questionnaire recognizes the Pembroke Corgi alias.', 'expected' => 'Typing Pembroke Corgi should surface Pembroke Welsh Corgi at the top.'],
                ['id' => 'breed_questionnaire_boston_alias', 'text' => 'Breed Questionnaire recognizes the Boston alias.', 'expected' => 'Typing Boston should surface Boston Terrier at the top.'],
                ['id' => 'breed_questionnaire_aussie_alias', 'text' => 'Breed Questionnaire recognizes the Aussie alias.', 'expected' => 'Typing Aussie should surface Australian Shepherd at the top.'],
                ['id' => 'breed_questionnaire_sheltie_alias', 'text' => 'Breed Questionnaire recognizes the Sheltie alias.', 'expected' => 'Typing Sheltie should surface Shetland Sheepdog at the top.'],
                ['id' => 'breed_questionnaire_dobie_alias', 'text' => 'Breed Questionnaire recognizes the Dobie alias.', 'expected' => 'Typing Dobie should surface Doberman Pinscher at the top.'],
                ['id' => 'breed_questionnaire_rottie_alias', 'text' => 'Breed Questionnaire recognizes the Rottie alias.', 'expected' => 'Typing Rottie should surface Rottweiler at the top.'],
                ['id' => 'breed_questionnaire_lab_alias', 'text' => 'Breed Questionnaire recognizes the Lab alias.', 'expected' => 'Typing Lab should surface Labrador Retriever at the top.'],
                ['id' => 'breed_questionnaire_gsp_alias', 'text' => 'Breed Questionnaire recognizes the GSP alias.', 'expected' => 'Typing GSP should surface German Shorthaired Pointer at the top.'],
                ['id' => 'breed_questionnaire_mal_alias', 'text' => 'Breed Questionnaire recognizes the Mal alias.', 'expected' => 'Typing Mal should surface Belgian Malinois at the top.'],
                ['id' => 'breed_questionnaire_viz_alias', 'text' => 'Breed Questionnaire recognizes the Viz alias.', 'expected' => 'Typing Viz should surface Vizsla at the top.'],
                ['id' => 'breed_questionnaire_heeler_alias', 'text' => 'Breed Questionnaire recognizes the Heeler alias.', 'expected' => 'Typing Heeler should surface Australian Cattle Dog at the top.'],
                ['id' => 'breed_questionnaire_blue_heeler_alias', 'text' => 'Breed Questionnaire recognizes the Blue Heeler alias.', 'expected' => 'Typing Blue Heeler should surface Australian Cattle Dog at the top.'],
                ['id' => 'breed_questionnaire_frenchie_alias', 'text' => 'Breed Questionnaire recognizes the Frenchie alias.', 'expected' => 'Typing Frenchie should surface French Bulldog at the top.'],
                ['id' => 'breed_questionnaire_berner_alias', 'text' => 'Breed Questionnaire recognizes the Berner alias.', 'expected' => 'Typing Berner should surface Bernese Mountain Dog at the top.'],
                ['id' => 'breed_questionnaire_newfie_alias', 'text' => 'Breed Questionnaire recognizes the Newfie alias.', 'expected' => 'Typing Newfie should surface Newfoundland at the top.'],
                ['id' => 'breed_questionnaire_goldie_alias', 'text' => 'Breed Questionnaire recognizes the Goldie alias.', 'expected' => 'Typing Goldie should surface Golden Retriever at the top.'],
                ['id' => 'breed_questionnaire_great_pyr_alias', 'text' => 'Breed Questionnaire recognizes the Great Pyr alias.', 'expected' => 'Typing Great Pyr should surface Great Pyrenees at the top.'],
                ['id' => 'breed_questionnaire_drilldown_mode', 'text' => 'Breed Questionnaire exposes a drill-down mode for family and size narrowing.', 'expected' => 'The questionnaire includes a drill-down panel that can narrow by breed family or working size.'],
                ['id' => 'breed_questionnaire_drilldown_alignment', 'text' => 'Breed Questionnaire drill-down mode keeps the result set narrow.', 'expected' => 'Submitting Toy drill-down filters should keep the top match in a toy or small breed band.'],
                ['id' => 'ai_training_assistant', 'text' => 'AI Training Assistant page loads for Pro users and free users see the Pro paywall.', 'expected' => 'Pro users get safety-aware troubleshooting while free users see the upgrade notice.'],
                ['id' => 'paywall_catalog_admin', 'text' => 'Admin paywall catalog page loads and can edit plan or service rows.', 'expected' => 'Admin can edit plan labels, gates, add-on services, and notes from inside the app, with inline row edits kept collapsed by default.'],
                ['id' => 'paywall_purchase_events_admin', 'text' => 'Admin paywall catalog shows recent Stripe purchase events.', 'expected' => 'Admin can review recent service purchases with service, user, dog, and amount details.'],
                ['id' => 'wearable_integrations', 'text' => 'Wearable Integrations page loads, lets the user create a connect code that opens the wearable bridge page or APK link, shows the wearable compatibility catalog, saves a wearable device setup, supports a tracker import path, and saves a wearable snapshot.', 'expected' => 'User can pair a wearable bridge, open the bridge page, download the APK link, review the wearable compatibility catalog, save the wearable device setup, import tracker activity minutes, battery percentage, and resting heart rate, record a wearable summary, and review recent syncs.'],
                ['id' => 'wearable_integrations_android', 'text' => 'Android bridge shows wearable sync summary and recent syncs for the active dog.', 'expected' => 'Android wearable panel loads the current wearable trend summary and a recent sync list.'],
                ['id' => 'certification_page', 'text' => 'Certification page loads and shows readiness tracking.', 'expected' => 'Certification tracking page displays the checklist and assessment snapshot.'],
                ['id' => 'admin_notification_test', 'text' => 'Admin Notification Test page loads and shows settings.', 'expected' => 'Admin can send email, SMS, or Telegram tests.'],
                ['id' => 'admin_profile_completion', 'text' => 'Admin Profile Completion page loads and shows missing required fields.', 'expected' => 'Admin can review completion counts and missing fields.'],
                ['id' => 'admin_found_dog_reports', 'text' => 'Admin Found Dog Reports page loads, collapses each report, and supports bulk status updates.', 'expected' => 'Admin can review found-dog submissions, select multiple reports, and move them between new, reviewing, contacted, resolved, closed, and archived.'],
                ['id' => 'api_tokens', 'text' => 'API Tokens page loads and can create/revoke tokens.', 'expected' => 'Admin can manage API tokens for the account.'],
                ['id' => 'api_wearables_endpoint', 'text' => 'Wearable API endpoint can record an automatic sync snapshot.', 'expected' => 'api/wearables.php accepts bearer-auth JSON and stores a wearable snapshot.'],
                ['id' => 'api_wearables_overview', 'text' => 'Wearable API overview endpoint returns the trend summary and recent sync events.', 'expected' => 'api/wearables.php GET returns a summary object and events list for the selected dog.'],
                ['id' => 'backup_tools', 'text' => 'Backup Tools page loads and exposes export/restore options.', 'expected' => 'Admin can download backups and start restore flow.'],
                ['id' => 'backup_csv_export', 'text' => 'Backup export CSV downloads.', 'expected' => 'export_backup.php returns the CSV log export.'],
                ['id' => 'backup_import_redirect', 'text' => 'Import Backup redirects to Backup Tools on direct GET.', 'expected' => 'import_backup.php sends the browser back to backup.php until a file is posted.'],
                ['id' => 'public_profile_questionnaire_link', 'text' => 'Public dog profile links to the Breed Questionnaire.', 'expected' => 'Public profile page exposes the questionnaire CTA.'],
                ['id' => 'public_profile_air_travel_link', 'text' => 'Public dog profile links to Air Travel Rights.', 'expected' => 'Public profile page exposes the flight guidance CTA.'],
                ['id' => 'admin_feedback', 'text' => 'Admin Feedback Reports page shows submitted feedback.', 'expected' => 'Submitted bug report is visible to admin.'],
                ['id' => 'admin_feedback_ai', 'text' => 'AI Issue Assistant page loads from the admin feedback workflow.', 'expected' => 'Admin can open the issue assistant and see a recommended status and next steps.'],
                ['id' => 'admin_business_costs', 'text' => 'Admin Business Costs page loads and shows live provider snapshot values plus cost trends.', 'expected' => 'Admin can review live Twilio, Render, Stripe, and ZeptoMail snapshot cards, a month-over-month cost trend panel, the editable cost ledger, Porkbun import area, and service pricing summary.'],
                ['id' => 'user_management', 'text' => 'Admin User Management page loads and master admin sees the purge controls.', 'expected' => 'Admin can inspect/manage users, and master admin can permanently purge a user and owned dogs.'],
                ['id' => 'feature_roadmap', 'text' => 'Admin Feature Roadmap page loads.', 'expected' => 'Flags/roadmap remain visible.'],
                ['id' => 'system_health', 'text' => 'System Health / DB status page loads.', 'expected' => 'Database status and migration info are readable.'],
            ],
        ],
        [
            'id' => 'security_and_privacy',
            'title' => 'Security and Privacy',
            'description' => 'Spot-check access control and private/public boundaries.',
            'items' => [
                ['id' => 'logged_out_protected', 'text' => 'Protected pages redirect when logged out.', 'expected' => 'Dashboard, Dog Access, Audit, Admin pages require login.'],
                ['id' => 'non_admin_blocked', 'text' => 'Non-admin account cannot open admin-only pages.', 'expected' => '403/admin-only behavior is shown.'],
                ['id' => 'shared_viewer_limit', 'text' => 'Viewer shared handler cannot perform owner-only actions.', 'expected' => 'Cannot transfer, revoke, or grant dog access.'],
                ['id' => 'owner_only_transfer', 'text' => 'Only current owner can send ownership transfer.', 'expected' => 'Shared handlers cannot transfer dog ownership.'],
                ['id' => 'qr_private_data', 'text' => 'Public QR profile does not expose private logs, medical records, account data, or app history.', 'expected' => 'Only public contact/return info is visible.'],
                ['id' => 'csrf_forms', 'text' => 'Important POST actions use CSRF token.', 'expected' => 'Forms do not submit without valid session/token.'],
            ],
        ],
        [
            'id' => 'cleanup_and_data_safety',
            'title' => 'Cleanup and Data Safety',
            'description' => 'Validate test data cleanup and avoid destructive mistakes.',
            'items' => [
                ['id' => 'e2e_cleanup_dry_run', 'text' => 'Run E2E cleanup dry-run locally before deleting test data.', 'expected' => 'Dry-run lists only intended E2E dogs/logs/media.'],
                ['id' => 'e2e_cleanup_yes', 'text' => 'Run E2E cleanup with --yes only after dry-run is correct.', 'expected' => 'Only matched E2E records are deleted.'],
                ['id' => 'media_cleanup_review', 'text' => 'Review media files before deleting.', 'expected' => 'No real user uploads are removed accidentally.'],
                ['id' => 'backup_before_major', 'text' => 'Take backup before major schema/data changes.', 'expected' => 'Backup exists before testing transfers/status/audit changes on important data.'],
            ],
        ],
    ];
}
