<?php

function getDogBreedsCatalog(): array
{
    $catalog = [
        'Labrador Retriever' => [
            'group' => 'Sporting',
            'temperament' => 'Friendly, steady, eager to please',
            'traits' => 'Highly trainable, food motivated, social, adaptable to public work',
            'notes' => 'Often strong service-dog candidates. Can be energetic when young and need regular exercise to stay settled.',
        ],
        'Golden Retriever' => [
            'group' => 'Sporting',
            'temperament' => 'Gentle, patient, affectionate',
            'traits' => 'Handler-focused, soft temperament, biddable, commonly successful in public access work',
            'notes' => 'Usually excellent with people. Coat care is heavier than short-coated breeds.',
        ],
        'German Shepherd Dog' => [
            'group' => 'Herding',
            'temperament' => 'Loyal, alert, confident',
            'traits' => 'Intelligent, responsive, protective tendencies, thrives with structure',
            'notes' => 'Can excel in service work with solid socialization. Needs careful training to avoid over-guarding or environmental sensitivity.',
        ],
        'Standard Poodle' => [
            'group' => 'Non-Sporting',
            'temperament' => 'Bright, attentive, sensitive',
            'traits' => 'Very trainable, athletic, often good for low-shed households',
            'notes' => 'Common service-dog choice. Regular grooming is a must.',
        ],
        'Bernese Mountain Dog' => [
            'group' => 'Working',
            'temperament' => 'Calm, affectionate, steady',
            'traits' => 'Large frame, people-oriented, generally gentle disposition',
            'notes' => 'Can suit mobility-style work, but heat tolerance and joint longevity should be watched closely.',
        ],
        'Great Dane' => [
            'group' => 'Working',
            'temperament' => 'Patient, friendly, composed',
            'traits' => 'Tall, easygoing, often naturally noticeable in public',
            'notes' => 'Can support some mobility-adjacent roles, but short lifespan and orthopedic issues are important considerations.',
        ],
        'Boxer' => [
            'group' => 'Working',
            'temperament' => 'Playful, loyal, energetic',
            'traits' => 'People-focused, animated, intelligent, can be goofy and strong',
            'notes' => 'May do well with experienced handlers. Needs impulse control and enough exercise.',
        ],
        'Doberman Pinscher' => [
            'group' => 'Working',
            'temperament' => 'Devoted, alert, responsive',
            'traits' => 'Fast learner, highly bonded, confident, athletic',
            'notes' => 'Can be excellent in trained hands, but public perception and guarding instincts require careful neutrality work.',
        ],
        'Rottweiler' => [
            'group' => 'Working',
            'temperament' => 'Calm, confident, devoted',
            'traits' => 'Stable with good breeding, powerful, trainable, deeply bonded',
            'notes' => 'Needs strong socialization and polished public manners. Public bias can be a factor.',
        ],
        'Newfoundland' => [
            'group' => 'Working',
            'temperament' => 'Sweet, calm, patient',
            'traits' => 'Large, gentle, slow-moving, often tolerant and people-friendly',
            'notes' => 'Can be comforting and steady, though size, drool, and heat sensitivity matter.',
        ],
        'Border Collie' => [
            'group' => 'Herding',
            'temperament' => 'Intense, responsive, energetic',
            'traits' => 'Extremely trainable, quick learner, high mental drive',
            'notes' => 'Brilliant but often more intensity than many service handlers want for daily public access.',
        ],
        'Australian Shepherd' => [
            'group' => 'Herding',
            'temperament' => 'Smart, loyal, energetic',
            'traits' => 'Fast learner, engaged, athletic, can be environmentally aware',
            'notes' => 'Can do well with active handlers, but sensitivity and herding tendencies may need extra shaping.',
        ],
        'Collie' => [
            'group' => 'Herding',
            'temperament' => 'Gentle, responsive, devoted',
            'traits' => 'Soft expression, handler-aware, trainable, often naturally attentive',
            'notes' => 'Can make solid service dogs with good confidence-building. Coat care varies by type.',
        ],
        'Shetland Sheepdog' => [
            'group' => 'Herding',
            'temperament' => 'Sensitive, bright, loyal',
            'traits' => 'Very trainable, tuned in to handler, compact size',
            'notes' => 'May fit small-dog task work, but some lines can be vocal or noise-sensitive.',
        ],
        'Corgi' => [
            'group' => 'Herding',
            'temperament' => 'Bold, clever, outgoing',
            'traits' => 'Portable, trainable, sturdy, expressive personality',
            'notes' => 'Can handle alert/response tasks well, but body structure limits mobility-style work.',
        ],
        'Belgian Malinois' => [
            'group' => 'Herding',
            'temperament' => 'Driven, intense, highly alert',
            'traits' => 'Exceptionally trainable, fast, high work ethic, environmentally sharp',
            'notes' => 'Usually too much dog for most service work homes unless the handler is very experienced and the dog is an unusually stable candidate.',
        ],
        'Great Pyrenees' => [
            'group' => 'Working',
            'temperament' => 'Calm, independent, watchful',
            'traits' => 'Large, steady, patient, slower decision style',
            'notes' => 'Can be emotionally steady, but independence can reduce precision and responsiveness for task work.',
        ],
        'Saint Bernard' => [
            'group' => 'Working',
            'temperament' => 'Gentle, calm, patient',
            'traits' => 'Very large, tolerant, affectionate',
            'notes' => 'Can be comforting and visible in public, but size, drool, and orthopedic limits matter.',
        ],
        'Mastiff' => [
            'group' => 'Working',
            'temperament' => 'Dignified, calm, protective',
            'traits' => 'Massive build, usually low energy, strong bonding',
            'notes' => 'Can be steady but often not as biddable or physically practical for many service tasks.',
        ],
        'Siberian Husky' => [
            'group' => 'Working',
            'temperament' => 'Independent, social, energetic',
            'traits' => 'Athletic, expressive, often friendly with strangers',
            'notes' => 'Usually harder to use in service work because independence can compete with handler focus.',
        ],
        'Alaskan Malamute' => [
            'group' => 'Working',
            'temperament' => 'Strong-willed, affectionate, steady',
            'traits' => 'Powerful, social, durable, often less handler-focused than retrievers',
            'notes' => 'Can be dependable in some homes but is not typically an easy service-dog breed.',
        ],
        'German Shorthaired Pointer' => [
            'group' => 'Sporting',
            'temperament' => 'Eager, energetic, intelligent',
            'traits' => 'Trainable, athletic, responsive, high exercise needs',
            'notes' => 'Can work well for active handlers, but exercise needs are significant.',
        ],
        'English Springer Spaniel' => [
            'group' => 'Sporting',
            'temperament' => 'Cheerful, biddable, affectionate',
            'traits' => 'Trainable, social, eager to work, medium size',
            'notes' => 'Often a nice middle ground for alert/response work. Some lines can be sensitive.',
        ],
        'Cocker Spaniel' => [
            'group' => 'Sporting',
            'temperament' => 'Sweet, merry, responsive',
            'traits' => 'Compact, affectionate, trainable, portable',
            'notes' => 'Can fit smaller service work roles well. Grooming and ear care matter.',
        ],
        'Brittany' => [
            'group' => 'Sporting',
            'temperament' => 'Bright, eager, sensitive',
            'traits' => 'Quick learner, athletic, handler-aware',
            'notes' => 'Can succeed with active handlers but may need extra help settling in busy environments.',
        ],
        'Vizsla' => [
            'group' => 'Sporting',
            'temperament' => 'Velcro, sensitive, eager',
            'traits' => 'Highly bonded, athletic, responsive, affectionate',
            'notes' => 'Can be wonderful for close-working teams, though some are too soft for heavy public stress.',
        ],
        'Weimaraner' => [
            'group' => 'Sporting',
            'temperament' => 'Bold, energetic, attached',
            'traits' => 'Athletic, intelligent, people-oriented, strong need for activity',
            'notes' => 'Can task well with the right handler, but energy and arousal levels need management.',
        ],
        'Flat-Coated Retriever' => [
            'group' => 'Sporting',
            'temperament' => 'Upbeat, social, eager',
            'traits' => 'Friendly, trainable, soft-mouthed, fun-loving',
            'notes' => 'Can resemble a lighter Golden/Lab style, though some stay very adolescent for a long time.',
        ],
        'Portuguese Water Dog' => [
            'group' => 'Working',
            'temperament' => 'Bright, active, engaging',
            'traits' => 'Trainable, lower shedding coat, athletic, people-oriented',
            'notes' => 'Can be a good option for some homes, but energy and grooming are real commitments.',
        ],
        'Miniature Poodle' => [
            'group' => 'Non-Sporting',
            'temperament' => 'Smart, lively, attentive',
            'traits' => 'Portable, trainable, often excellent for alerts',
            'notes' => 'Very practical for smaller task sets. Grooming remains high maintenance.',
        ],
        'Toy Poodle' => [
            'group' => 'Toy',
            'temperament' => 'Bright, alert, devoted',
            'traits' => 'Tiny, smart, portable, often highly attuned to handler changes',
            'notes' => 'Best suited for alert/response rather than physical support tasks.',
        ],
        'Bichon Frise' => [
            'group' => 'Non-Sporting',
            'temperament' => 'Cheerful, affectionate, social',
            'traits' => 'Small, adaptable, friendly, lower shedding coat',
            'notes' => 'Can fit psychiatric alert/response roles. Coat maintenance is significant.',
        ],
        'Havanese' => [
            'group' => 'Toy',
            'temperament' => 'Sociable, gentle, bright',
            'traits' => 'Small, portable, people-oriented, often easy to live with',
            'notes' => 'Good candidate for small-dog public access and alert-type tasks.',
        ],
        'Cavalier King Charles Spaniel' => [
            'group' => 'Toy',
            'temperament' => 'Affectionate, soft, friendly',
            'traits' => 'Portable, social, naturally people-focused',
            'notes' => 'Lovely temperament for companionship and emotional grounding. Health screening is especially important in this breed.',
        ],
        'Papillon' => [
            'group' => 'Toy',
            'temperament' => 'Happy, sharp, agile',
            'traits' => 'Very trainable, portable, surprisingly athletic',
            'notes' => 'Excellent for alert tasks and travel-friendly teams. Not for physical support work.',
        ],
        'Yorkshire Terrier' => [
            'group' => 'Toy',
            'temperament' => 'Bold, devoted, alert',
            'traits' => 'Tiny, portable, often highly tuned to routine and handler patterns',
            'notes' => 'Can fit alert-oriented work, though some individuals can be vocal or reactive.',
        ],
        'Shih Tzu' => [
            'group' => 'Toy',
            'temperament' => 'Friendly, calm, affectionate',
            'traits' => 'Portable, low-demand energy, people-friendly',
            'notes' => 'Can be practical for companionship and some response tasks. Heat care and grooming matter.',
        ],
        'Pomeranian' => [
            'group' => 'Toy',
            'temperament' => 'Lively, bold, alert',
            'traits' => 'Tiny, portable, attentive, expressive',
            'notes' => 'Can work for alert tasks if barking and arousal are well managed.',
        ],
        'Chihuahua' => [
            'group' => 'Toy',
            'temperament' => 'Loyal, alert, sensitive',
            'traits' => 'Very portable, strongly bonded, quick to notice routine changes',
            'notes' => 'Can suit alert/response work, but confidence and neutrality in public are key.',
        ],
        'Beagle' => [
            'group' => 'Hound',
            'temperament' => 'Cheerful, curious, social',
            'traits' => 'Food motivated, friendly, compact, scent-driven',
            'notes' => 'Can be good-natured partners, though scent distraction and vocalizing may complicate service work.',
        ],
        'Basset Hound' => [
            'group' => 'Hound',
            'temperament' => 'Easygoing, affectionate, patient',
            'traits' => 'Calm, social, strong nose, slower pace',
            'notes' => 'Can be emotionally steady but often less precise and less eager to work than top service breeds.',
        ],
        'Whippet' => [
            'group' => 'Hound',
            'temperament' => 'Gentle, quiet, sensitive',
            'traits' => 'Light build, calm indoors, affectionate, typically low odor',
            'notes' => 'Can be lovely for low-key teams, though environmental sensitivity varies.',
        ],
        'Greyhound' => [
            'group' => 'Hound',
            'temperament' => 'Quiet, gentle, reserved',
            'traits' => 'Calm in the house, elegant, low-maintenance coat',
            'notes' => 'Some do very well in public, but sensitivity and startle recovery should be assessed individually.',
        ],
        'Rhodesian Ridgeback' => [
            'group' => 'Hound',
            'temperament' => 'Independent, loyal, composed',
            'traits' => 'Athletic, reserved with strangers, strong-willed',
            'notes' => 'Can be stable but usually requires more handler skill than classic service breeds.',
        ],
        'Dalmatian' => [
            'group' => 'Non-Sporting',
            'temperament' => 'Bright, active, outgoing',
            'traits' => 'Athletic, smart, eye-catching, high stamina',
            'notes' => 'Can be versatile but needs enough physical outlet and steady public neutrality work.',
        ],
        'Mixed Breed' => [
            'group' => 'Mixed',
            'temperament' => 'Varies by individual dog',
            'traits' => 'Can combine strengths from multiple breeds; actual working qualities depend on the dog in front of you',
            'notes' => 'For service work, individual temperament, health, trainability, and recovery matter more than label alone.',
        ],
        'Unknown / Rescue Mix' => [
            'group' => 'Mixed',
            'temperament' => 'Unknown until observed over time',
            'traits' => 'Traits can emerge gradually as the dog settles and matures',
            'notes' => 'Use the notes field to record what you actually see: confidence, recovery, neutrality, sociability, sound sensitivity, and drive.',
        ],
        'Other / Custom' => [
            'group' => 'Custom',
            'temperament' => 'Enter your own description',
            'traits' => 'Use when the dog is a rare breed, cross, or specific working line not listed here',
            'notes' => 'You can still type any breed name manually. The dropdown is there to help, not restrict.',
        ],
    ];

    $details = [
        'Labrador Retriever' => ['size' => 'Large', 'weight_range' => '55-80 lbs', 'coat_type' => 'Short double coat', 'shedding' => 'High', 'exercise_level' => 'High'],
        'Golden Retriever' => ['size' => 'Large', 'weight_range' => '55-75 lbs', 'coat_type' => 'Medium-long double coat', 'shedding' => 'High', 'exercise_level' => 'High'],
        'German Shepherd Dog' => ['size' => 'Large', 'weight_range' => '50-90 lbs', 'coat_type' => 'Medium double coat', 'shedding' => 'High', 'exercise_level' => 'High'],
        'Standard Poodle' => ['size' => 'Large', 'weight_range' => '40-70 lbs', 'coat_type' => 'Curly single coat', 'shedding' => 'Low', 'exercise_level' => 'Moderate to high'],
        'Bernese Mountain Dog' => ['size' => 'Giant', 'weight_range' => '70-115 lbs', 'coat_type' => 'Long double coat', 'shedding' => 'High', 'exercise_level' => 'Moderate'],
        'Great Dane' => ['size' => 'Giant', 'weight_range' => '100-175 lbs', 'coat_type' => 'Short coat', 'shedding' => 'Moderate', 'exercise_level' => 'Moderate'],
        'Boxer' => ['size' => 'Large', 'weight_range' => '50-80 lbs', 'coat_type' => 'Short coat', 'shedding' => 'Moderate', 'exercise_level' => 'High'],
        'Doberman Pinscher' => ['size' => 'Large', 'weight_range' => '60-100 lbs', 'coat_type' => 'Short coat', 'shedding' => 'Moderate', 'exercise_level' => 'High'],
        'Rottweiler' => ['size' => 'Large', 'weight_range' => '80-135 lbs', 'coat_type' => 'Short double coat', 'shedding' => 'Moderate', 'exercise_level' => 'Moderate to high'],
        'Newfoundland' => ['size' => 'Giant', 'weight_range' => '100-150 lbs', 'coat_type' => 'Long double coat', 'shedding' => 'High', 'exercise_level' => 'Moderate'],
        'Border Collie' => ['size' => 'Medium', 'weight_range' => '30-55 lbs', 'coat_type' => 'Smooth or rough double coat', 'shedding' => 'Moderate', 'exercise_level' => 'Very high'],
        'Australian Shepherd' => ['size' => 'Medium', 'weight_range' => '40-65 lbs', 'coat_type' => 'Medium double coat', 'shedding' => 'Moderate to high', 'exercise_level' => 'Very high'],
        'Collie' => ['size' => 'Large', 'weight_range' => '50-75 lbs', 'coat_type' => 'Rough or smooth coat', 'shedding' => 'Moderate to high', 'exercise_level' => 'Moderate'],
        'Shetland Sheepdog' => ['size' => 'Small to medium', 'weight_range' => '15-25 lbs', 'coat_type' => 'Long double coat', 'shedding' => 'High', 'exercise_level' => 'Moderate to high'],
        'Corgi' => ['size' => 'Small to medium', 'weight_range' => '22-38 lbs', 'coat_type' => 'Medium double coat', 'shedding' => 'High', 'exercise_level' => 'Moderate'],
        'Belgian Malinois' => ['size' => 'Large', 'weight_range' => '40-80 lbs', 'coat_type' => 'Short double coat', 'shedding' => 'Moderate', 'exercise_level' => 'Very high'],
        'Great Pyrenees' => ['size' => 'Giant', 'weight_range' => '85-160 lbs', 'coat_type' => 'Long double coat', 'shedding' => 'High', 'exercise_level' => 'Moderate'],
        'Saint Bernard' => ['size' => 'Giant', 'weight_range' => '120-180 lbs', 'coat_type' => 'Short or long coat', 'shedding' => 'Moderate to high', 'exercise_level' => 'Low to moderate'],
        'Mastiff' => ['size' => 'Giant', 'weight_range' => '120-230 lbs', 'coat_type' => 'Short coat', 'shedding' => 'Low to moderate', 'exercise_level' => 'Low to moderate'],
        'Siberian Husky' => ['size' => 'Medium', 'weight_range' => '35-60 lbs', 'coat_type' => 'Medium double coat', 'shedding' => 'High', 'exercise_level' => 'Very high'],
        'Alaskan Malamute' => ['size' => 'Large', 'weight_range' => '70-100 lbs', 'coat_type' => 'Thick double coat', 'shedding' => 'High', 'exercise_level' => 'High'],
        'German Shorthaired Pointer' => ['size' => 'Large', 'weight_range' => '45-70 lbs', 'coat_type' => 'Short coat', 'shedding' => 'Moderate', 'exercise_level' => 'Very high'],
        'English Springer Spaniel' => ['size' => 'Medium', 'weight_range' => '40-55 lbs', 'coat_type' => 'Medium coat with feathering', 'shedding' => 'Moderate', 'exercise_level' => 'High'],
        'Cocker Spaniel' => ['size' => 'Medium', 'weight_range' => '20-30 lbs', 'coat_type' => 'Medium-silky coat', 'shedding' => 'Moderate', 'exercise_level' => 'Moderate'],
        'Brittany' => ['size' => 'Medium', 'weight_range' => '30-40 lbs', 'coat_type' => 'Dense coat with feathering', 'shedding' => 'Moderate', 'exercise_level' => 'Very high'],
        'Vizsla' => ['size' => 'Large', 'weight_range' => '45-65 lbs', 'coat_type' => 'Short coat', 'shedding' => 'Low to moderate', 'exercise_level' => 'Very high'],
        'Weimaraner' => ['size' => 'Large', 'weight_range' => '55-90 lbs', 'coat_type' => 'Short coat', 'shedding' => 'Low to moderate', 'exercise_level' => 'Very high'],
        'Flat-Coated Retriever' => ['size' => 'Large', 'weight_range' => '55-75 lbs', 'coat_type' => 'Medium-long flat coat', 'shedding' => 'Moderate', 'exercise_level' => 'High'],
        'Portuguese Water Dog' => ['size' => 'Medium', 'weight_range' => '35-60 lbs', 'coat_type' => 'Curly or wavy single coat', 'shedding' => 'Low', 'exercise_level' => 'High'],
        'Miniature Poodle' => ['size' => 'Small', 'weight_range' => '10-20 lbs', 'coat_type' => 'Curly single coat', 'shedding' => 'Low', 'exercise_level' => 'Moderate'],
        'Toy Poodle' => ['size' => 'Toy', 'weight_range' => '4-10 lbs', 'coat_type' => 'Curly single coat', 'shedding' => 'Low', 'exercise_level' => 'Moderate'],
        'Bichon Frise' => ['size' => 'Small', 'weight_range' => '12-18 lbs', 'coat_type' => 'Curly double coat', 'shedding' => 'Low', 'exercise_level' => 'Moderate'],
        'Havanese' => ['size' => 'Small', 'weight_range' => '7-13 lbs', 'coat_type' => 'Long silky coat', 'shedding' => 'Low', 'exercise_level' => 'Moderate'],
        'Cavalier King Charles Spaniel' => ['size' => 'Small', 'weight_range' => '13-18 lbs', 'coat_type' => 'Silky medium coat', 'shedding' => 'Moderate', 'exercise_level' => 'Low to moderate'],
        'Papillon' => ['size' => 'Toy', 'weight_range' => '5-10 lbs', 'coat_type' => 'Silky coat with fringe', 'shedding' => 'Low to moderate', 'exercise_level' => 'Moderate'],
        'Yorkshire Terrier' => ['size' => 'Toy', 'weight_range' => '4-7 lbs', 'coat_type' => 'Long silky single coat', 'shedding' => 'Low', 'exercise_level' => 'Moderate'],
        'Shih Tzu' => ['size' => 'Toy', 'weight_range' => '9-16 lbs', 'coat_type' => 'Long double coat', 'shedding' => 'Low', 'exercise_level' => 'Low to moderate'],
        'Pomeranian' => ['size' => 'Toy', 'weight_range' => '3-7 lbs', 'coat_type' => 'Long double coat', 'shedding' => 'Moderate to high', 'exercise_level' => 'Moderate'],
        'Chihuahua' => ['size' => 'Toy', 'weight_range' => '3-6 lbs', 'coat_type' => 'Smooth or long coat', 'shedding' => 'Low to moderate', 'exercise_level' => 'Low to moderate'],
        'Beagle' => ['size' => 'Medium', 'weight_range' => '20-30 lbs', 'coat_type' => 'Short coat', 'shedding' => 'Moderate', 'exercise_level' => 'Moderate to high'],
        'Basset Hound' => ['size' => 'Medium', 'weight_range' => '40-65 lbs', 'coat_type' => 'Short coat', 'shedding' => 'Moderate', 'exercise_level' => 'Low to moderate'],
        'Whippet' => ['size' => 'Medium', 'weight_range' => '25-40 lbs', 'coat_type' => 'Short coat', 'shedding' => 'Low', 'exercise_level' => 'Moderate'],
        'Greyhound' => ['size' => 'Large', 'weight_range' => '60-80 lbs', 'coat_type' => 'Short coat', 'shedding' => 'Low', 'exercise_level' => 'Moderate'],
        'Rhodesian Ridgeback' => ['size' => 'Large', 'weight_range' => '65-90 lbs', 'coat_type' => 'Short coat', 'shedding' => 'Low to moderate', 'exercise_level' => 'Moderate to high'],
        'Dalmatian' => ['size' => 'Large', 'weight_range' => '45-70 lbs', 'coat_type' => 'Short coat', 'shedding' => 'High', 'exercise_level' => 'High'],
        'Mixed Breed' => ['size' => 'Varies', 'weight_range' => 'Varies', 'coat_type' => 'Varies', 'shedding' => 'Varies', 'exercise_level' => 'Varies'],
        'Unknown / Rescue Mix' => ['size' => 'Unknown', 'weight_range' => 'Unknown', 'coat_type' => 'Unknown', 'shedding' => 'Unknown', 'exercise_level' => 'Unknown until observed'],
        'Other / Custom' => ['size' => 'Custom', 'weight_range' => 'Custom', 'coat_type' => 'Custom', 'shedding' => 'Custom', 'exercise_level' => 'Custom'],
    ];

    foreach ($catalog as $breedName => &$breedInfo) {
        $breedInfo = array_merge([
            'size' => 'Varies',
            'weight_range' => 'Varies',
            'coat_type' => 'Varies',
            'shedding' => 'Varies',
            'exercise_level' => 'Varies',
        ], $breedInfo, $details[$breedName] ?? []);
    }
    unset($breedInfo);

    return $catalog;
}
